#! /bin/sh

TITLE=$1
DAYS_BACK=$2

python crds_header.py $TITLE
python crds_jira.py $DAYS_BACK
python crds_server_status.py jwst ops https://jwst-crds.stsci.edu $DAYS_BACK
python crds_server_status.py hst ops https://hst-crds.stsci.edu $DAYS_BACK
python crds_server_status.py hst test https://hst-crds-test.stsci.edu $DAYS_BACK

