#! /bin/sh

cat header.rst
python crds_server_status.py jwst dev https://jwst-crds-dev.stsci.edu report.rst
python crds_server_status.py hst dev https://hst-crds-dev.stsci.edu report.rst
python crds_jira.py

