#!/usr/bin/env python3
#-*-python-*-

import sys

import smtplib

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def crds_mail(from_addr, to_addr, subject, html_path):

    # Create message container - the correct MIME type is multipart/alternative.
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = from_addr
    msg['To'] = to_addr

    with open(html_path) as html_file:
        html = html_file.read()
    part = MIMEText(html, 'html')
    msg.attach(part)

    # Send the message via local SMTP server.
    s = smtplib.SMTP('localhost')

    # sendmail function takes 3 arguments: sender's address, recipient's address
    # and message to send - here it is sent as one string.
    s.sendmail(from_addr, to_addr, msg.as_string())

if __name__ == "__main__":
    crds_mail(*sys.argv[1:])
        
