# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrdsRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Title')),
                ('date_needed', models.DateField(verbose_name='Date Needed')),
                ('requester', models.CharField(choices=[('ReDCaT', 'ReDCaT'), ('MESA', 'MESA'), ('CRDS', 'CRDS'), ('CAL', 'CAL'), ('Archive', 'Archive'), ('SDP', 'SDP'), ('Other', 'Other')], max_length=64, verbose_name='Requester')),
                ('description_of_functionality', models.TextField(verbose_name='Description of Functionality')),
                ('benefit', models.TextField(verbose_name='Benefit')),
                ('cost_of_not_implementing', models.TextField(verbose_name='Cost of not Implementing')),
                ('alternative_methods_of_achieving', models.TextField(verbose_name='Alternative Methods')),
                ('additional_notes', models.TextField(verbose_name='Additional Notes')),
            ],
        ),
    ]
