# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crdsrequestmodel',
            name='affected_crds_systems',
            field=models.TextField(blank=True, default='', verbose_name='Affected CRDS Systems (core, bestrefs, certify, diff, rules updates, miscellaneous tools, server database features, server reference submissions, server rules submissions, command line submissions, server bestrefs functions, server RPC functions, web formatting, documentation)'),
        ),
        migrations.AddField(
            model_name='crdsrequestmodel',
            name='fte_estimate',
            field=models.FloatField(default=0.0, verbose_name='FTE Estimate (days)'),
        ),
        migrations.AddField(
            model_name='crdsrequestmodel',
            name='implementing_groups',
            field=models.TextField(blank=True, default='', verbose_name='Implementing Groups (CRDS,  ReDCaT,  SDP,  Archive, CAL, ...)'),
        ),
        migrations.AddField(
            model_name='crdsrequestmodel',
            name='related_external_systems',
            field=models.TextField(blank=True, default='', verbose_name='Related External Systems (ReDCaT submission front end, CAL code, Archive Delivery, Pipeline Syncing, Pipeline repro fetch, CRDS services to Archive, Archive repro parameters for CRDS, Remote Users, Remote Institutions, Archive Databases)'),
        ),
        migrations.AddField(
            model_name='crdsrequestmodel',
            name='required_support',
            field=models.TextField(blank=True, default='', verbose_name='Required Support (specs, VMs, storage, proxies, reviews, ...)'),
        ),
        migrations.AddField(
            model_name='crdsrequestmodel',
            name='resolution',
            field=models.CharField(choices=[('opened', 'opened'), ('assigned', 'assigned'), ('completed', 'completed'), ('rejected', 'rejected')], default='opened', max_length=64, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='requester',
            field=models.CharField(blank=True, choices=[('ReDCaT', 'ReDCaT'), ('MESA', 'MESA'), ('CRDS', 'CRDS'), ('CAL', 'CAL'), ('Archive', 'Archive'), ('SDP', 'SDP'), ('Other', 'Other')], default='', max_length=64, verbose_name='Requester'),
        ),
    ]
