# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20171205_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='crdsrequestmodel',
            name='affected_projects',
            field=models.CharField(default='', help_text='HST, JWST, ...', max_length=64, verbose_name='Affected Projects'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='affected_crds_systems',
            field=models.TextField(blank=True, default='', help_text='core, bestrefs, certify, diff, rules updates, miscellaneous tools, server database features, server reference submissions, server rules submissions, command line submissions, server bestrefs functions, server RPC functions, web formatting, documentation', verbose_name='Affected CRDS Systems'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='implementing_groups',
            field=models.TextField(blank=True, default='', help_text='CRDS,  ReDCaT,  SDP,  Archive, CAL, ...', verbose_name='Implementing Groups'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='related_external_systems',
            field=models.TextField(blank=True, default='', help_text='ReDCaT submission front end, CAL code, Archive Delivery, Pipeline Syncing, Pipeline repro fetch, CRDS services to Archive, Archive repro parameters for CRDS, Remote Users, Remote Institutions, Archive Databases', verbose_name='Related External Systems'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='required_support',
            field=models.TextField(blank=True, default='', help_text='specs, VMs, storage, proxies, reviews, ...', verbose_name='Required Support'),
        ),
    ]
