# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20171205_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='additional_notes',
            field=models.TextField(blank=True, default='', verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='alternative_methods_of_achieving',
            field=models.TextField(blank=True, default='', verbose_name='Alternative Methods'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='benefit',
            field=models.TextField(blank=True, default='', verbose_name='Benefit'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='cost_of_not_implementing',
            field=models.TextField(blank=True, default='', verbose_name='Cost of not Implementing'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='date_needed',
            field=models.DateField(blank=True, null=True, verbose_name='Date Needed'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='description_of_functionality',
            field=models.TextField(blank=True, default='', verbose_name='Description of Functionality'),
        ),
        migrations.AlterField(
            model_name='crdsrequestmodel',
            name='fte_estimate',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='FTE Estimate (days)'),
        ),
    ]
