#! /bin/sh -x

###
### create the install directory
###

secret=6700
private_ro=6750
private_rw=6770
public=6744
immutable=444

function create_dir {
    mkdir -p $2 $3 $4 $5 $6 $7 $8 $9
    chmod $1 $2
}

# CRDS log files from e.g. Apache and cron
chmod $secret $CRDS_LOGS

# Keys and passwords with security implications
chmod $secret $CRDS_SECRETS

chmod $private_ro $CRDS_SERVER_ISILON

# The primary working copy for deliveries, nominally owned by CRDS.
# Delivery files are links which last until received by OPUS.
create_dir $private_rw $CRDS_DELIVERY_DIR

# The temporary directory where CRDS/CDBS team deliverers can scp files.
create_dir $private_rw $CRDS_INGEST_DIR

# Where CRDS writes out delivery catalog files when delivering files
# to downstream systems like the archive.  Catalog files persist.
create_dir $private_ro $CRDS_CATALOG_DIR

# The temporary directory where uploaded files are initially stored.
create_dir $private_ro $FILE_UPLOAD_TEMP_DIR

# This is the server cache and reference staging area.
create_dir $public $map_path_full
create_dir $public $ref_path_full
create_dir $public $config_path_full

create_dir $secret $install_dir
create_dir $secret $install_dir/python/bin

# This is a place for matplotlib to store cache files.  We don't actually
# try to put any config there, and only the apache server knows to use it.
create_dir $secret $install_dir/mplconfigdir

create_dir $secret $web
create_dir $secret $web/logs 
create_dir $secret $web/db_backups
create_dir $secret $web/run 
create_dir $secret $web/conf  
create_dir $secret $web/wsgi-scripts

case ${server_mode} in

    "django" )
	;;

    *) 
	echo "Setting permissions"

	chmod $public ${ref_path}
	chmod $public ${ref_path_full}

	chmod $public ${map_path}
	chmod $public ${map_path_full}

	chmod $secret ${install_dir}
	for dir in $install_dir/*
	do
	    chmod $secret $dir  # default to secret
	done
	chmod $private_ro ${CRDS_CATALOG_DIR}
	for dir in ${CRDS_DELIVERY_DIR} ${CRDS_INGEST_DIR} ${FILE_UPLOAD_TEMP_DIR}
	do
	    chmod $private_rw $dir
	    chmod g+s $dir
	done
	;;
esac

