#! /bin/sh -x

# This install script is heavily based on the PyETC install script
# CRDS is intended to use the same LAMP stack as pyetc, with emphasis on Python

# ----------------------------------------------------------
#  CRDS file system setup
# ----------------------------------------------------------

./_file_system_setup

# ----------------------------------------------------------
#  CRDS Server systemd service setup
# ----------------------------------------------------------

# Done by ITSD:    cp host/crds.service  /etc/systemd/system
rm -f /home/crds/crds_start
cp host/crds_start /home/crds
chmod 500 /home/crds/crds_start

rm -f /home/crds/crds_stop
cp host/crds_stop /home/crds
chmod 500 /home/crds/crds_stop

# ----------------------------------------------------------
#  CRDS Server Apache configuration and setup
# ----------------------------------------------------------

./_meta_server_setup

# ----------------------------------------------------------
#  CRDS Code Installation and static file
# ----------------------------------------------------------
rm -rf $CRDS_INSTALL_DIR/python/lib/python/crds*    # XXXXX
rm -rf $CRDS/static   # XXXXXX

#  INSTALL CORE CRDS CLIENT LIBRARY
(
    cd ../CRDS; ./install
)   # --home $install_dir/python)

# INSTALL crds_server 
(./save_version >sources/git_version.py; 

cp host/* ${CRDS_SERVER_SCRIPTS}
cp host/logrotate.cfg ${CRDS_SERVER_LOGS}

config="sources/configs/config.${CRDS_USECASE}.${CRDS_PROJECT}.py"
echo "Using configuration " ${config}
cp ${config} sources/site_config.py

crds_database="sources/configs/database.${CRDS_USECASE}.${CRDS_PROJECT}.py"
echo "Using crds_database" ${crds_database}
cp ${crds_database} sources/crds_database.py

cd sources; 
# python setup.py install --force --home $install_dir/python |& grep -v /static |& grep -v /test_data |& grep -v /templates)
python setup.py install --force |& grep -v /static |& grep -v /test_data |& grep -v /templates
)

echo "Silently installing static files."
crds_manage collectstatic  <<EOF |& grep -v /static |& grep -v /test_data |& grep -v /templates
yes
EOF

