#! /bin/sh -x

# This install script is heavily based on the PyETC install script
# CRDS is intended to use the same LAMP stack as pyetc, with emphasis on Python

rm env.*

source ./make_env # $1 $2 $3 $4 $5

# This is required in production environments which don't include Django in
# the main Python stack.
# ./init_pkgs $1 $2 $3 $4 $5

. ./make_env.tmp
rm make_env.tmp

if [ X$1 = X-r ]
then
	rc=1
else
	rc=0
fi

case "$noreload"
in
[tT]rue)        noreload="--noreload"
        ;;
esac

###
### eliminate excess verbosity in the setup.py steps so we can see any
### other errors that come out
###
pyquiet=-q

###
### create the install directory
###

secret=6700
private_ro=6750
private_rw=6770
public=6744
immutable=444

function create_dir {
    mkdir -p $2 $3 $4 $5 $6 $7 $8 $9
    chmod $1 $2
}

chmod $secret $install_dir/..
chmod $secret $install_dir/../database

chmod $private_ro $CRDS_SERVER_ISILON

# The primary working copy for deliveries, nominally owned by CRDS.
# Delivery files are links which last until received by OPUS.
create_dir $private_rw $CRDS_DELIVERY_DIR

# The temporary directory where CRDS/CDBS team deliverers can scp files.
create_dir $private_rw $CRDS_INGEST_DIR

# Where CRDS writes out delivery catalog files when delivering files
# to downstream systems like the archive.  Catalog files persist.
create_dir $private_ro $CRDS_CATALOG_DIR

# The temporary directory where uploaded files are initially stored.
create_dir $private_ro $FILE_UPLOAD_TEMP_DIR

# This is a drop-off dir for hand crafted SSB-made references and mappings.
# create_dir $private_rw ${CRDS_INGEST_DIR}_ssb
rm -rf ${CRDS_INGEST_DIR}_ssb

# The directory where dynamic mapping bundles are kept
# create_dir $secret $CRDS_ARCHIVE_CACHE_DIR
# rm $CRDS_ARCHIVE_CACHE_DIR/*
rm -rf $CRDS_ARCHIVE_CACHE_DIR

# This is the server cache and reference staging area.
create_dir $public $map_path_full
create_dir $public $ref_path_full
create_dir $public $config_path_full

create_dir $secret $install_dir
create_dir $secret $install_dir/python/bin

# This is a place for matplotlib to store cache files.  We don't actually
# try to put any config there, and only the apache server knows to use it.
create_dir $secret $install_dir/mplconfigdir

create_dir $secret $install_dir/server
create_dir $secret $install_dir/server/logs 
create_dir $secret $install_dir/server/db_backups
create_dir $secret $install_dir/server/run 
create_dir $secret $install_dir/server/conf  
create_dir $secret $install_dir/server/wsgi-scripts

cp host/rc_script /home/crds
chmod 500 /home/crds/rc_script

cp host/rc_script_DONT_DELETE /home/crds
chmod 500 /home/crds/rc_script_DONT_DELETE

###
### special cases for each type of web server we might be using
###
case "$servertype"
in

# apache with mod_python
mod_wsgi)
	apache_version=`/usr/sbin/httpd -v | sed -n 's?Server version: Apache/??p'`
	case "$apache_version"
	in
	2.4.*)
		dso_version=2.4
		;;
	2.2.*)
		dso_version=2.2
		;;
	2.0.*)
		dso_version=2.0
		;;
	*)
		echo do not have a config for this apache version -"$apache_version"-
		exit 1
		;;
	esac

	cp servers/httpd.mod_wsgi.conf $install_dir/server/conf/httpd.conf
	perl -p -e"s/SUB_PORT/$port/g" servers/ssl.${dso_version}.conf >ssl.tmp
	mv ssl.tmp $install_dir/server/conf/ssl.conf
	cp servers/*.wsgi $install_dir/server/wsgi-scripts
	rm -f $install_dir/lib/mod_wsgi.so
	mkdir -p $install_dir/lib
	ln -s ${CRDS_STACK}/lib/mod_wsgi.so $install_dir/lib
   
	cat servers/apache_dso.$dso_version >>  $install_dir/server/conf/httpd.conf

	if [ "$apachemod" = "" ]
	then
		apachemod=$third/lib/apache
		export apachemod
		cp ${install_dir}/lib/mod_wsgo.so ${apachemod}
	fi	
	if [ ! -f $apachemod/mod_wsgi.so ]
	    then
	    echo "WARNING: NO MOD_WSGI FOUND (possibly installed later by init_pkgs)"
	fi

#         python ${SERVER_SOURCES}/sh_config.py add_ldap_auth >tmp
#        . tmp

        if [ "$add_ldap_auth" = "True" ]
        then
		if [ "$rc" = 1 ]
		then
			echo do not use authentication in a release candidate system
			exit 1
		fi
                cat servers/httpd.add_ldap >> $install_dir/server/conf/httpd.conf
        fi

        sed -e "s?SUB_APACHEMOD?$apachemod?g" -e "s?SUB_DIR?$install_dir?g" -e "s?SUB_PORT?$port?g" -e "s?SUB_CDBS?$PYSYN_CDBS?g"  -e "s?SUB_CRDS_PATH?$CRDS_PATH?g" < $install_dir/server/conf/httpd.conf > tmp
        mv tmp $install_dir/server/conf/httpd.conf

        # create the shell script that runs the server.  We want everything that
        # has gotten in to env.csh so far, but nothing that comes later.  (Everything
        # that comes later is for debug environments; we don't want to contaminate
        # our production environment with possible dependencies on that data.)
        (
        cat env.sh
	echo "nohup memcached -m 32M -s /tmp/memcached.sock </dev/null |& cat >>${install_dir}/server/logs/memcached.log &"
	echo "disown -h %1"
        echo "/usr/sbin/httpd -f $install_dir/server/conf/httpd.conf"
        ) > run

	(
	cat env.sh
        echo 'kill `cat '$install_dir'/server/run/httpd.pid` '
	echo 'killall memcached'
	)  > stop

        ln -fs /etc/httpd/modules $install_dir/server/

        ln -fs /etc/httpd/conf/magic $install_dir/server/conf/

        ;;

# django development server
django)
	if [ "$rc" = 1 ]
	then
		echo do not use django server for release candidate
		exit 1
	fi

        # hostname=`hostname`
	hostname=localhost

        (
	cat env.csh
        echo "cd $install_dir/python/lib/python/crds_server"
	echo "nohup memcached -m 32M -s /tmp/memcached.sock </dev/null |& cat >>${install_dir}/server/logs/memcached.log &"
	echo "onintr control_c"
        echo "python manage.py runserver $noreload $hostname:$port"
	echo "control_c:"
	echo "echo"
	echo "echo 'Killing memcached...'"
	echo "killall memcached"
	echo "echo 'Quitting...'"
        ) > run

        (
        echo '#! /bin/csh'
	echo "killall memcached"
        ) > stop

        ;;

# anything else is unrecognized
*)
        echo ''
        echo unknown server type $servertype
        echo ''
        # do not need a default case for server type after this
        exit 1
        ;;
esac

#
chmod 755 ./run ./stop

# copy over the static files
if [ `uname` = 'Linux' ]
then
        cpio_quiet='--quiet'
else
        cpio_quiet=''
fi

# find htdocs | grep -v '\.svn' | cpio $cpio_quiet -oc | ( cd $install_dir ; cpio $cpio_quiet -icdum  )

case "$rc"
in
1)	rm -f $install_dir/htdocs/status.shtml
	;;
esac

case "$debug_javascript"
in
[Tt]rue)
        # copy the debug value into the
        sed 's/^enable_debug=.*$/enable_debug=true;/' <  htdocs/etcstatic/validate_general.1.js  > $install_dir/htdocs/etcstatic/validate_general.1.js
        ;;
esac

###
### install the python packages that we use
###

if [ "$CRDS_USECASE" != "django" ]
then
    rm -rf $CRDS_INSTALL_DIR/python/lib/python/crds*
    rm -rf $CRDS/static
fi

#  INSTALL CORE CRDS CLIENT LIBRARY
(cd ../CRDS; ./install --home $install_dir/python)

# INSTALL crds_server 
(./save_version >sources/git_version.py; cd sources; python setup.py install --force --home $install_dir/python |& grep -v /static |& grep -v /test_data |& grep -v /templates)

# SYNC the Django database for the CRDS server & catalog
# (cd $install_dir/python/lib/python/crds_server ; python manage.py syncdb)
# echo "Done syncing db"

###
### tell the user what we did
###

echo ''
echo Installed in:
echo '  '$install_dir
echo URL is
echo '  'http://`hostname`:$port
echo 'to start the server:'
echo '  './run
echo 'to stop the server:'
case "$servertype"
in
django)
        echo '  'type control-c
        ;;
*)
        echo '  './stop
        ;;
esac

echo 'to get an environment like the web server will see:'
echo '  source env.csh'

echo ''

case ${server_mode}
    in
    "dev" | "test" | "ops" | "ait" | "bit" | "cit" | "dit" ) 
	echo "Setting permissions"

	chmod $public ${ref_path}
	chmod $public ${ref_path_full}
	# chmod -f $immutable ${ref_path_full}/*

	chmod $public ${map_path}
	chmod $public ${map_path_full}
	# chmod -f $immutable ${map_path_full}/*

	# find $CRDS_PATH -type d | xargs chmod 6755

	chmod $secret ${install_dir}
	for dir in $install_dir/*
	do
	    chmod $secret $dir  # default to secret
	done
	chmod $private_ro ${CRDS_CATALOG_DIR}
	chmod $private_ro ${CRDS_ARCHIVE_CACHE_DIR}   # Where mapping bundles go
	for dir in ${CRDS_DELIVERY_DIR} ${CRDS_INGEST_DIR} ${CRDS_INGEST_DIR}_ssb ${FILE_UPLOAD_TEMP_DIR}
	do
	    chmod $private_rw $dir
	    chmod g+s $dir
	done
	;;
    "django" )
	;;
esac

echo "Silently installing static files."
./manage collectstatic <<EOF
yes
EOF
