#! /bin/csh

# Script to remove temporary install files which show up as ? in svn status

rm -rf sources/build
rm -f servers/httpd.conf*
rm -f ssl.tmp
rm -rf crds_report/dist crds_report/build crds_report/crds_report.egg-info*
