#! /bin/sh

# =======================================================================
# Init server environment by installing third_party package list.

source ./make_env

./metaw install @crds_packages
./metaw clean

