#! /bin/tcsh -x

# =======================================================================
# Init server environment

if (($1 != "hst") && ($1 != "jwst")) then
	echo 'usage: ./init [jwst|hst]'
	exit -1;
endif

set observatory=$1
shift

if (($1 != "django")) then #  && ($1 != "dev") && ($1 != "ops") && ($1 != "test")) then
    # This has bitrotted too much to use to reinitialize the operational servers.
	echo 'usage: ./init [jwst|hst] [django]'
	exit -1;
endif

set mode=$1
shift

cd `dirname $0`
source env.csh

cd `dirname $0`/tools

# =======================================================================

if (($mode == "test") || ($mode == "django") || ($mode == "dev")) then
    echo -n "Test account password? "
    set password=$<
    echo "Adding test user"
    python adduser.py test jmiller@stsci.edu "$password"
endif

# =======================================================================
# Install prototype mappings (no serial number) in server cache automatically
# Deliver "real" or cloned mappings and references using submit references followed by submit
# mappings.
set mapping_source_dir=`python get_mapping_dir.py ${observatory}`
set map_path_full=${CRDS_PATH}/mappings/${observatory}
set ref_path_full=${CRDS_PATH}/references/${observatory}

echo
echo "Copying prototype mappings from ${mapping_source_dir} to ${map_path_full}"
echo

mkdir -p ${map_path_full}
chmod -R g-w ${CRDS_PATH}
chmod -R o-rwx ${CRDS_PATH}

foreach mapping (`ls -1 ${mapping_source_dir}/*.*map | grep -v 0`)
  cp -v ${mapping} ${map_path_full}
end

chmod 444 ${map_path_full}/*
chmod 444 ${ref_path_full}/*

# =======================================================================
if ($observatory == "hst") then
    echo "Linking files from Central Store /grp/crds/hst/..."
	mkdir -p ${CRDS_PATH}/mappings/hst
    foreach file (`ls /grp/crds/hst/mappings/hst/*`)
        ln -s /grp/crds/hst/mappings/hst/$file  ${CRDS_PATH}/mappings/hst/$file 
    end
	mkdir -p ${CRDS_PATH}/references/hst
    foreach file (`ls /grp/crds/hst/references/*`)
        ln -s /grp/crds/hst/references/hst/$file  ${CRDS_PATH}/references/hst/$file  
    end

    unsetenv CRDS_SERVER_URL
    python -m crds.list --all --hst --cached-mappings --full-path >hst_mappings
    python -m crds.list --all --hst --cached-references --full-path >hst_references
    
    # see command line options
    python add_files.py --hst --add-slow-fields --reinit-slow-fields --deliver @hst_mappings --set-contexts
    python add_files.py --hst --deliver @hst_references

    # Add just enough slow fields to pass unit tests
    ( cd ../sources/interactive/test_data; \
      cp u1r1346ri_bia.fits n9i1435li_crr.fits t3420177i_drk.fits w2r1956ri_idc.fits n9n16196i_a2d.fits t291659mi_ccd.fits u5d2012li_bpx.fits q911321oi_osc.fits wbj1825si_imp.fits v8816168i_pfl.fits w7j1705di_fls.fits ubi1853qi_mdz.fits ${CRDS_PATH}/references/hst; \
    )

    python add_slow_fields.py u1r1346ri_bia.fits n9i1435li_crr.fits t3420177i_drk.fits w2r1956ri_idc.fits n9n16196i_a2d.fits t291659mi_ccd.fits u5d2012li_bpx.fits q911321oi_osc.fits wbj1825si_imp.fits v8816168i_pfl.fits w7j1705di_fls.fits ubi1853qi_mdz.fit

    python hack_context_date.py hst.pmap 2013-06-01T00:00:00

# =======================================================================
else if ($observatory == "jwst") then
    echo "Linking files from Central Store /grp/crds/jwst/..."
	mkdir -p ${CRDS_PATH}/mappings/jwst
    ln -s /grp/crds/jwst/mappings/jwst/* ${CRDS_PATH}/mappings/jwst
	mkdir -p ${CRDS_PATH}/references/jwst
	ln -s /grp/crds/jwst/references/jwst/* ${CRDS_PATH}/references/jwst
    python -m crds.list --jwst --cached-mappings --full-path >jwst_mappings
    python -m crds.list --jwst --cached-references --full-path >jwst_references
    python add_files.py --jwst --add-slow-fields --reinit-slow-fields --deliver @jwst_mappings --set-contexts
    python add_files.py --jwst --deliver @jwst_references
    python hack_context_date.py jwst.pmap 2013-06-01T00:00:00
else
	echo "unknown observatory"
	exit -1;
endif
