#! /bin/tcsh

# =======================================================================
# Init server environment by installing third_party package list.

./metaw install @crds_packages
./metaw clean

