#! /bin/bash

# Original RC scripts based on STScI checkenv and tcsh, obsolete
# Adapted to no-checkenv by linking .cshrc to checkenv's .setenv

cp host/dot_setenv $HOME/.setenv
cp host/dot_alias $HOME/.alias
rm -f ~/.cshrc
ln -s $HOME/.setenv $HOME/.cshrc

# ----------------------------------------------------------
#  CRDS file system setup
# ----------------------------------------------------------

./_file_system_setup

# ----------------------------------------------------------
#  CRDS Server systemd service setup
# ----------------------------------------------------------

# Done by ITSD:    cp host/crds.service  /etc/systemd/system
rm -f /home/crds/crds_start
cp host/crds_start /home/crds
chmod 500 /home/crds/crds_start

rm -f /home/crds/crds_stop
cp host/crds_stop /home/crds
chmod 500 /home/crds/crds_stop

# ----------------------------------------------------------
#  CRDS Server Apache configuration and setup
# ----------------------------------------------------------

./_meta_server_setup

# ----------------------------------------------------------
#  CRDS Code Installation and static file
# ----------------------------------------------------------
rm -rf $CRDS_INSTALL_DIR/python/lib/python/crds*    # XXXXX
rm -rf $CRDS/static   # XXXXXX

#  INSTALL CORE CRDS CLIENT LIBRARY
(
    cd ../CRDS; ./install
)   # --home $install_dir/python)

# INSTALL crds_server 
(./save_version >sources/git_version.py; 

rm -rf ${CRDS_SERVER_SCRIPTS}
mkdir -p ${CRDS_SERVER_SCRIPTS}
cp host/* ${CRDS_SERVER_SCRIPTS}

cp host/logrotate.cfg ${CRDS_SERVER_LOGS}

cd sources; 
# python setup.py install --force --home $install_dir/python |& grep -v /static |& grep -v /test_data |& grep -v /templates)
python setup.py install --force |& grep -v /static |& grep -v /test_data |& grep -v /templates
)

echo "Silently installing static files."
crds_manage collectstatic  <<EOF |& grep -v /static |& grep -v /test_data |& grep -v /templates
yes
EOF

