#! /bin/sh 

# This script creates env.csh and installs site specific database and config files.

if [ "$1" != "hst" ] && [ "$1" != "jwst" ]; then
	echo 'usage: ./install [jwst|hst] [django|dev|test|ops|bit|b6it|dit|ait]'
	exit -1
fi

observatory=$1; shift

if [ "$1" != "django" ] && [ "$1" != "dev" ] && [ "$1" != "ops" ] && [ "$1" != "test" ] && \
    [ "$1" != "ait" ] && [ "$1" != "bit" ]  &&  [ "$1" != "cit" ] &&  [ "$1" != "dit" ] && ["$1" != "syslab" ]; then
	echo 'usage: ./install [jwst|hst] [django|dev|ops|test|ait|bit|cit|dit|syslab]'
	exit -1;
fi

server_mode=$1; shift

export SERVER_SOURCES=sources   # CRDS_server/sources

###
### gather config values that we need in this script
###

(
        echo '#! /bin/csh'
        echo 'setenv PYTHONPATH '$PYTHONPATH
        echo 'unsetenv DJANGO_SETTINGS_MODULE PYSYN_CDBS CRDS_DJANGO_SERVER'
	echo 'setenv SERVER_PORT ' $port
) > env.csh

perl -p -e's/^setenv (\w+)\s+(.*)/export \1="\2"/g' env.csh >env.sh
perl -pi -e 's./bin/csh./bin/sh.g' env.sh
perl -pi -e 's/unsetenv/unset/g' env.sh

