#! /bin/tcsh

# =======================================================================
# Run the meta installer script to install third party packages from source
# into the server library

# =======================================================================
# "meta" is a generic Python installer script which installs different
# kinds of packages from source code, including non-python libraries
# and Python C extensions which use them.

# "metaw" is a wrapper script for "meta" which sets standard switches
# and environment variables to make calling "meta" convenient and to
# install to the CRDS server library directory.

# =======================================================================
# a .meta file is a .tar which includes source as well as "build" and
# "install" scripts of some kind.

# a .tar.gz is a standard UNIX compressed tarball which is essentially
# built using: ./configure; make install

# a .pygz file is a standard Python package .tar.gz, built using
# python setup.py install

# =======================================================================

# META_PREFIX is roughly equivalent to a custom /usr/local for meta.  
# It typically has lib, bin, etc. subdirectories,  just like /usr/local would.

# =======================================================================
# source the environment created by install or init_pkgs
source env.csh

setenv META_PREFIX "$CRDS_INSTALL_DIR"
setenv PACKAGE_PATH "."
setenv CFLAGS "-I$CRDS_INSTALL_DIR/include -L$CRDS_INSTALL_DIR/lib"
setenv LDFLAGS "-L$CRDS_INSTALL_DIR/lib"

cd third_party;

./meta --python=python --home=${CRDS_INSTALL_DIR}/python  $*

