#! /bin/sh

cd `dirname $0`

if [ "$1" != "hst" ] && [ "$1" != "jwst" ]; then
	echo 'usage: ./install [jwst|hst] [django|test]'
	exit -1
fi

if [ "$2" != "django" ] && [ "$2" != "dev" ] && [ "$2" != "test" ] && [ "$2" != "ops" ]; then
	echo 'usage: ./install [jwst|hst] [django|dev|test|ops]'
	exit -1
fi

# svn update

# (cd ../CRDS; svn update)

echo "==========================================================="
echo "Stopping server"
echo "==========================================================="
./stop  $1 $2 

echo "==========================================================="
echo "Installing crds.server Python Django application"
echo "==========================================================="
./install $1 $2

echo "==========================================================="
echo "Re-starting server"
echo "==========================================================="
./run $1 $2

