#! /bin/sh

cd `dirname $0`

if [ "$1" != "hst" ] && [ "$1" != "jwst" ]; then
	echo 'usage: ./install [jwst|hst] [dev|test]'
	exit -1
fi

if [ "$2" != "dev" ] && [ "$2" != "vmdvlp" ] && [ "$2" != "test" ] && [ "$2" != "prod" ]; then
	echo 'usage: ./install [jwst|hst] [dev|vmdvlp|test|prod]'
	exit -1
fi

# svn update

# (cd ../CRDS; svn update)

./stop  >& /dev/null

./install $1 $2

./run $1 $2

