#! /bin/tcsh

echo "This command will clear the database. ARE YOU SURE you wish to proceed?"
set ans=$<
if ($ans != "Y"  &&  $ans != "y") then
    echo "Quitting."
    exit -1
endif

foreach app (interactive jsonapi locking fileupload stats jpoll)
    echo "Clearing $app"
    ./manage sqlclear $app | ./manage dbshell
end
./manage syncdb

