#! /bin/tcsh

# <observatory=hst|jwst> <server_mode=django|dev|test|prod>

set observatory = "$1"
set server_mode = "$2"

if ($server_mode == django) then
echo "installing $1 $2..."
./install $1 $2 <<EOF
yes
EOF
endif

source env.csh

cd sources

if ($# > 2) then
    echo "Using explicit tests " $3 $4 $5 $6 $7 $8 $9
    # subsequent parameters are apps to test
    python manage.py test $3 $4 $5 $6 $7 $8 $9 --verbosity=2
else if ($observatory == "jwst") then
    echo "Using implied JWST tests " ALL
    python manage.py test --verbosity=2
else
    echo "Using implied HST tests " ALL
    python manage.py test --verbosity=2
endif

