#! /bin/tcsh

# usage: ./runtests <parameters to "manage.py test"...>

cd ${CRDS}/CRDS_server

if ( $1 == "live") then
    shift;
    set switch_port=0
else 
    set switch_port=1
endif

if ($switch_port) then
    tools/set_backup_url True
else
    echo "================================================================================"
    echo "Testing on live server"
    echo "================================================================================"
endif

source env.csh

setenv LOG ${CRDS}/CRDS_server/runtests.${CRDS_PROJECT}.${CRDS_USECASE}.err

echo "Removing any stale test databases"
./manage dbshell <<EOF  >& /dev/null
drop database test_crds_${CRDS_PROJECT}_${CRDS_USECASE};
EOF

cd sources


# setenv TEST_CMD "python -u manage.py test --verbosity=2 --with-coverage --cover-erase --cover-html --cover-package=crds -cover-branches --cover-html-dir=$CRDS/CRDS_server/coverage"

# Removed coverage switches due to incompatibility with django-1.8.2
setenv TEST_CMD "python -u manage.py test --verbosity=2"


if ($# > 0) then
    # subsequent parameters are apps to test
    echo "================================================================================"
    echo "Running tests $*"
    echo "================================================================================"
else 
    echo "================================================================================"
    echo "Running implied tests ALL"
    echo "================================================================================"
endif
$TEST_CMD $* |& tee $LOG

if ($switch_port) then
    cd ${CRDS}/CRDS_server
    tools/set_backup_url False
endif
