# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 17:02

import crds_server.interactive.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='unique name of this model.', max_length=64)),
                ('blob', models.TextField(default='{}', help_text='repr() of value of this blob,  probably repr(dict).')),
                ('user', models.CharField(default='', help_text='user who performed this action', max_length=64)),
                ('date', models.CharField(default='', help_text='date of this action', max_length=26)),
                ('action', models.CharField(choices=[('mass import', 'mass import'), ('submit file', 'submit file'), ('blacklist', 'blacklist'), ('new context', 'new context'), ('batch submit', 'batch submit'), ('set default context', 'set default context'), ('delete references', 'delete references'), ('add references', 'add references'), ('add_files tool', 'add_files tool')], default='', help_text='name of action performed', max_length=64)),
                ('filename', models.CharField(default='', help_text='unique name of this model.', max_length=64)),
                ('observatory', models.CharField(default='hst', help_text='observatory this action applied to.', max_length=8)),
                ('instrument', models.CharField(blank=True, default='', help_text='instrument this action applied to.', max_length=32)),
                ('filekind', models.CharField(blank=True, default='', help_text='filekind this action applied to.', max_length=32)),
                ('why', models.TextField(blank=True, default='', help_text='reason this action was performed')),
                ('details', models.TextField(blank=True, default='', help_text='supplementary info')),
            ],
            options={
                'db_table': 'crds_hst_actions',
            },
        ),
        migrations.CreateModel(
            name='ContextHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='unique name of this model.', max_length=64)),
                ('start_date', models.DateTimeField()),
                ('context', models.CharField(default='', help_text='name of .pmap assigned to for this kind of context.', max_length=64)),
                ('state', models.CharField(choices=[('operational', 'operational'), ('edit', 'edit'), ('versions', 'versions')], default='operational', max_length=32)),
                ('description', models.TextField(default='routine update', help_text='Reason for the switch to this context.')),
            ],
            options={
                'db_table': 'crds_hst_context_history',
                'ordering': ('start_date', 'context'),
            },
        ),
        migrations.CreateModel(
            name='ContextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='unique name of this model.', max_length=64)),
                ('context', models.CharField(default='', help_text='name of .pmap assigned to for this kind of context.', max_length=64)),
            ],
            options={
                'db_table': 'crds_hst_contexts',
            },
        ),
        migrations.CreateModel(
            name='CounterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='unique name of this model.', max_length=64)),
                ('counter', models.IntegerField(default=0, help_text='Value of the counter.')),
            ],
            options={
                'db_table': 'crds_hst_counters',
            },
        ),
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='unique name of this model.', max_length=64)),
                ('blob', models.TextField(default='{}', help_text='repr() of value of this blob,  probably repr(dict).')),
                ('state', models.CharField(choices=[('delivered', 'delivered'), ('submitted', 'submitted'), ('archiving', 'archiving'), ('archiving-failed', 'archiving-failed'), ('archived', 'archived'), ('operational', 'operational'), ('uploaded', 'uploaded'), ('cancelled', 'cancelled')], default='delivered', help_text='operational status of this file.', max_length=32)),
                ('blacklisted', models.BooleanField(default=False, help_text='If True, this file should not be used, transitive to referencers.')),
                ('rejected', models.BooleanField(default=False, help_text='If True, this file should not be used, non-transitive.')),
                ('observatory', models.CharField(choices=[('hst', 'hst'), ('jwst', 'jwst')], default='hst', help_text='observatory associated with file', max_length=8)),
                ('instrument', models.CharField(choices=[('acs', 'acs'), ('cos', 'cos'), ('nicmos', 'nicmos'), ('stis', 'stis'), ('wfc3', 'wfc3'), ('wfpc2', 'wfpc2'), ('unknown', 'unknown')], default='', help_text='instrument associated with file', max_length=16)),
                ('filekind', models.CharField(choices=[('apdestab', 'apdestab'), ('apertab', 'apertab'), ('atodfile', 'atodfile'), ('atodtab', 'atodtab'), ('backtab', 'backtab'), ('badttab', 'badttab'), ('biacfile', 'biacfile'), ('biasfile', 'biasfile'), ('bpixtab', 'bpixtab'), ('brftab', 'brftab'), ('brsttab', 'brsttab'), ('ccdtab', 'ccdtab'), ('cdstab', 'cdstab'), ('cfltfile', 'cfltfile'), ('crrejtab', 'crrejtab'), ('d2imfile', 'd2imfile'), ('darkfile', 'darkfile'), ('deadtab', 'deadtab'), ('dfltfile', 'dfltfile'), ('dgeofile', 'dgeofile'), ('disptab', 'disptab'), ('drkcfile', 'drkcfile'), ('echsctab', 'echsctab'), ('exstab', 'exstab'), ('flatfile', 'flatfile'), ('flshfile', 'flshfile'), ('fluxtab', 'fluxtab'), ('gactab', 'gactab'), ('geofile', 'geofile'), ('gsagtab', 'gsagtab'), ('halotab', 'halotab'), ('hvtab', 'hvtab'), ('idctab', 'idctab'), ('illmfile', 'illmfile'), ('imphttab', 'imphttab'), ('inangtab', 'inangtab'), ('lamptab', 'lamptab'), ('lfltfile', 'lfltfile'), ('maskfile', 'maskfile'), ('mdriztab', 'mdriztab'), ('mlintab', 'mlintab'), ('mofftab', 'mofftab'), ('nlinfile', 'nlinfile'), ('noisfile', 'noisfile'), ('npolfile', 'npolfile'), ('offtab', 'offtab'), ('oscntab', 'oscntab'), ('pctab', 'pctab'), ('pctetab', 'pctetab'), ('pedsbtab', 'pedsbtab'), ('pfltfile', 'pfltfile'), ('phatab', 'phatab'), ('phottab', 'phottab'), ('pmodfile', 'pmodfile'), ('pmskfile', 'pmskfile'), ('proftab', 'proftab'), ('riptab', 'riptab'), ('rnlcortb', 'rnlcortb'), ('saacntab', 'saacntab'), ('saadfile', 'saadfile'), ('sdctab', 'sdctab'), ('shadfile', 'shadfile'), ('snkcfile', 'snkcfile'), ('spottab', 'spottab'), ('sptrctab', 'sptrctab'), ('spwcstab', 'spwcstab'), ('srwtab', 'srwtab'), ('tdctab', 'tdctab'), ('tdffile', 'tdffile'), ('tdstab', 'tdstab'), ('teltab', 'teltab'), ('tempfile', 'tempfile'), ('tracetab', 'tracetab'), ('twozxtab', 'twozxtab'), ('walktab', 'walktab'), ('wcptab', 'wcptab'), ('wf4tfile', 'wf4tfile'), ('xtractab', 'xtractab'), ('xwlkfile', 'xwlkfile'), ('ywlkfile', 'ywlkfile'), ('zprattab', 'zprattab'), ('unknown', 'unknown')], default='', help_text='dataset keyword associated with this file', max_length=16)),
                ('type', models.CharField(choices=[('reference', 'reference'), ('mapping', 'mapping')], default='', help_text='type of file,  reference data or CRDS rule or context', max_length=32)),
                ('derived_from', models.CharField(default='none', help_text='Previous version of this file this one was based on.', max_length=128)),
                ('sha1sum', models.CharField(default='none', help_text='Hex sha1sum of file contents as delivered', max_length=40)),
                ('delivery_date', models.DateTimeField(default=datetime.datetime.now, help_text='Date file was received by CRDS.')),
                ('activation_date', models.DateTimeField(default=datetime.datetime(2050, 1, 1, 0, 0), help_text='Date file first listed in an operational context.')),
                ('useafter_date', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), help_text='Dataset date after which this file is a valid reference.')),
                ('change_level', models.CharField(choices=[('SEVERE', 'SEVERE'), ('MODERATE', 'MODERATE'), ('TRIVIAL', 'TRIVIAL')], default='SEVERE', help_text='Affect of changes in this file relative to preceding version on science results', max_length=16)),
                ('pedigree', models.CharField(blank=True, default='', help_text='From PEDIGREE, reference characterization, e.g. GROUND 16/07/2008 16/07/2010', max_length=80)),
                ('reference_file_type', models.CharField(blank=True, default='', help_text='From REFTYPE,  description of file type.', max_length=80)),
                ('size', models.BigIntegerField(default=-1, help_text='size of file in bytes.')),
                ('uploaded_as', models.CharField(blank=True, default='', help_text='original upload filename', max_length=80)),
                ('creator_name', models.CharField(blank=True, default='', help_text='person who made this file,  possibly/likely not the submitter', max_length=80)),
                ('deliverer_user', models.CharField(blank=True, default='', help_text='username who uploaded the file', max_length=80)),
                ('deliverer_email', models.CharField(blank=True, default='', help_text="person's e-mail who uploaded the file", max_length=80)),
                ('description', models.TextField(blank=True, default='none', help_text='Brief rationale for changes to this file.')),
                ('catalog_link', models.CharField(blank=True, default='', max_length=128)),
                ('replaced_by_filename', models.CharField(blank=True, default='', max_length=128)),
                ('comment', models.TextField(blank=True, default='none', help_text='from DESCRIP keyword of reference file.')),
                ('aperture', models.CharField(blank=True, default='none', help_text='from APERTURE keyword of reference file.', max_length=80)),
                ('history', models.TextField(blank=True, default='none', help_text='History extracted from reference file.')),
            ],
            options={
                'db_table': 'crds_hst_catalog',
            },
            bases=(models.Model, crds_server.interactive.models.FileBlobRepairMixin),
        ),
        migrations.CreateModel(
            name='RemoteContextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='unique name of this model.', max_length=64)),
                ('observatory', models.CharField(default='none', help_text='Observatory this context applies to.', max_length=32)),
                ('kind', models.CharField(default='none', help_text='operational, edit, etc.', max_length=64)),
                ('key', models.CharField(default='none', help_text='Observatory this context applies to.', max_length=128)),
                ('context', models.CharField(default='none', help_text='Name of context in use by remote cache.', max_length=64)),
            ],
            options={
                'db_table': 'crds_hst_remote_context',
            },
        ),
        migrations.CreateModel(
            name='RepeatableResultBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='unique name of this model.', max_length=64)),
                ('blob', models.TextField(default='{}', help_text='repr() of value of this blob,  probably repr(dict).')),
            ],
            options={
                'db_table': 'crds_hst_results',
            },
        ),
    ]
