#! /bin/csh

setenv CRDS_STACK ${CRDS}/crds_stacks/crds_17
setenv META_PREFIX ${CRDS_STACK}

rm -rf ${CRDS_STACK}
mkdir ${CRDS_STACK}
cd ${CRDS}/crds_stacks/installer3

cd build
rm *.err
./meta clean >& /dev/null
./meta install @base  |& tee ${CRDS_STACK}/base.err

setenv PATH ${CRDS_STACK}/bin:${PATH}
rehash

# Install the entire base to get mercurial... for this.
../src/pull_local

rm -rf ${CRDS_STACK}
mkdir ${CRDS_STACK}
./meta clean >& /dev/null
./meta install @crds  |& tee ${CRDS_STACK}/crds.err
./meta clean >& /dev/null

rehash
hg summary |& tee ${CRDS_STACK}/hg.summary
hg status |& tee ${CRDS_STACK}/hg.status

