#! /bin/tcsh -f

if ( $#argv < 1 ) then
    echo "usage: capture <context> [--strict] [--no-update] [bestrefs parameters...]"
    echo
    echo "Captures the current catalog parameters in a regression test store for <context>"
    exit 1
endif

# setenv REGRESS $CRDS/regress/`echo $1 | cut -d'.' -f1`
setenv REGRESS $CRDS_PERSISTENT_LOCAL/regress/`datetag`
echo "Capturing regression inputs and results to $REGRESS"

rm -rf $REGRESS
mkdir -p $REGRESS
cd $REGRESS

# Capture server headers to .json files,  comparing CRDS to catalog bestrefs
crds list --config |& tee capture_config.err
crds_catalog_capture $* >& capture.err
summarize_bestrefs_log capture.err

gzip *.json *.errs

