#! /bin/csh

# This utility is intended to be run in a cronjob to periodically clear expired server
# instrument locks.

python <<EOF
import django
django.setup()
from crds_server.interactive import locks
locks.clear_expired_locks()
EOF

