#! /bin/csh

cd ${CRDS_INSTALL_DIR}/CRDS_server
source env.csh
python <<EOF
import os

import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "crds_server.settings")
django.setup()

from crds_server.interactive import models

models.clear_cache()
EOF
