#! /usr/bin/env python
#-*-python-*-

# Indiscriminantly wipe out all instrument locks (see also clear_expired_locks)

import django
django.setup()

from crds_server.locking import models

models.Lock.objects.all().delete()

