#! /bin/tcsh
#
# This is the rc script that starts the CRDS web server at system boot time.
# This script is intended to be run by user "crds".
# It simulates a login by sourcing the crds .setenv file.
#
source /home/crds/.setenv   # or skip this and just use a standard login environment for /bin/tcsh

nohup memcached -m 32M -s /tmp/memcached.sock </dev/null |& cat >>${CRDS_SERVER_LOGS}/memcached.log &

/usr/sbin/httpd -f ${CRDS_SERVER_SETUP}/conf/httpd.conf

crontab <${CRDS_SERVER_SCRIPTS}/crontab

exit 0

