#! /bin/tcsh
set dir=`dirname $0`
cd $dir
set dir=`pwd`
crds
./clean

$dir/pygrep . $*
$dir/pygrep ../CRDS_server/sources $*
$dir/pygrep ../CRDS_server/tools $*
$dir/pygrep ../hst_gentools $*
$dir/pygrep ../jwst_gentools $*

