#! /usr/bin/env python
import sys
import datetime

datestr = datetime.datetime.now().isoformat("-")

if len(sys.argv) == 1:
    print(datestr[:-7])
else:
    resolution = {
        "year":4,
        "month":7,
        "day":10,
        "hour":13,
        "minute":16,
        "second":19,
        "msec":23,
        "usec":26,
        }[sys.argv[1]]
    print(datestr[:resolution])
