#! /usr/bin/env python

from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division
from __future__ import absolute_import
from future import standard_library
standard_library.install_aliases()
from builtins import *

import sys
import datetime

datestr = datetime.datetime.now().isoformat("-")

if len(sys.argv) == 1:
    print(datestr[:-7])
else:
    resolution = {
        "year":4,
        "month":7,
        "day":10,
        "hour":13,
        "minute":16,
        "second":19,
        "msec":23,
        "usec":26,
        }[sys.argv[1]]
    print(datestr[:resolution])
