#! /usr/bin/env python

from __future__ import unicode_literals
from __future__ import print_function
from __future__ import division
from __future__ import absolute_import
from future import standard_library
standard_library.install_aliases()
from builtins import *
import sys
from astropy.io import fits as pyfits

def stub(fits):
    print("Deleting data in ", repr(fits))
    hdus = pyfits.open(fits)
    for hdu in hdus:
        hdu.data = None
    hdus.writeto(fits, clobber=True)

for fits in sys.argv[1:]:
    stub(fits)

