#! /usr/bin/env python
#-*-python-*-

from astropy.io import fits
from crds.core.pysh import *

usage("<keyword> [extension] <filenames...>", 2, 2**20)

if re.match("^\d+$", sys.argv[2]):
   extension = int(sys.argv[2])
   del sys.argv[2]

keyword = sys.argv[1]
filenames = sys.argv[2:]

for filename in filenames:
   with fits.open(filename) as hdulist:
      for i, hdu in enumerate(hdulist):
         try:
            print(repr(filename), keyword + "[{}]".format(i), "=", hdu.header[keyword])
         except KeyError:
            pass

