#! /usr/bin/env python

import os

import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "crds_server.settings")
django.setup()

import crds
from crds.core import pysh, heavy_client, log
from crds import list

from crds_server import config

log.info("Priming web cache (nominally memcached) by pre-fetching pages.")

log.info("Fetching index page")
pysh.out_err("wget ${CRDS_SERVER_URL} -O-")

log.info("Fetching server configuration")
info = heavy_client.get_config_info(os.environ["CRDS_PROJECT"])

list.ListScript("crds.list --all --references --mappings --verbosity=70")()

default_ctx  = crds.get_cached_mapping(info["operational_context"])

for mapping in default_ctx.mapping_names():
    if mapping.endswith(".rmap"):
        log.info("Priming", repr(mapping))
        pysh.out("wget ${CRDS_SERVER_URL}/context_table/" +  mapping + " -O-")

