#! /bin/tcsh

set dir=$1
shift;

if ( "$1" == "--web" ) then
    set web=1
    shift;
else
    set web=0
endif

if ( "$1" == "--ignore-case" ) then
    set ignore_case=-i
    shift;
else
    set ignore_case=""
endif

find $dir  -name '*.py' | xargs grep $ignore_case "$*"
if ( "$web" == "1" ) then
    find $dir  -name '*.html' | xargs grep $ignore_case "$*"
    find $dir  -name '*.js' | xargs grep $ignore_case "$*"
endif

