#! /bin/tcsh

set dir=$1
shift;

if ( "$1" == "--web" ) then
    set web=1
    shift;
else
    set web=0
endif

find $dir  -name '*.py' | xargs grep "$*"
if ( "$web" == "1" ) then
    find $dir  -name '*.html' | xargs grep "$*"
    find $dir  -name '*.js' | xargs grep "$*"
endif

