#! /bin/tcsh
#
# This is the rc script that starts the CRDS web server at system boot time.
# This script is intended to be run by user "crds".
# It simulates a login by sourcing the crds .setenv file.
#
source /home/crds/.setenv   # or skip this and just use a standard login environment for /bin/tcsh

cd ${CRDS}/CRDS_server

source env.csh

switch ($1)
  case start:
    ./run
    crontab <host/crontab
    breaksw
  case stop:
    crontab </dev/null
    ./stop
    breaksw
  case status:
    sed 's/^/PID=/' < ${CRDS_INSTALL_DIR}/server/run/httpd.pid
    breaksw
  default:
    echo "Usage: $0 {start|stop|status}"
    exit 1
    breaksw  
endsw

exit 0

