#! /bin/tcsh

if ( $#argv < 1 ) then
    echo "usage: regress <context> [--strict] [bestrefs parameters...]"
    echo
    echo "Does bestrefs regression from a test store for <context> created by 'capture'."
    exit 1
endif

setenv REGRESS $CRDS/regress/`echo $1 | cut -d'.' -f1`
echo "Running bestrefs regression using inputs from $REGRESS"

mkdir -p $REGRESS/crds_updated

cd $REGRESS/crds_updated
gunzip *.gz
python -m crds.list --config |& tee config.err
crds_json_regress $* --dump-unique-errors --unique-errors-file INSTRUMENT_regress_unique_err.ids >& regress.err
summarize_bestrefs_log regress.err
gzip -f *

