#! /bin/csh

# usage:   restore_server
# restores the last nightly backup for this server.

cd ${CRDS}/CRDS_server
source env.csh
set_backup_url True
source env.csh
mirror_server ${CRDS_PROJECT} ${CRDS_USECASE} ${CRDS_SERVER_URL}
