#! /bin/tcsh -f -x

echo "Setting cache file permissions at `date`"
chmod 444 ${CRDS_PATH}/mappings/${CRDS_PROJECT}/* 
chmod 444 ${CRDS_PATH}/references/${CRDS_PROJECT}/*
chmod 644 ${CRDS_PATH}/config/${CRDS_PROJECT}/* 

