#! /usr/bin/env python
#-*-python-*-
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division
from __future__ import absolute_import
from future import standard_library
standard_library.install_aliases()
from builtins import *

import sys

from crds import pysh

def main():
    pysh.usage("<log_file>", 1)
    log  = sys.argv[1]
    if log.endswith(".gz"):
        print("Uncompressing", log)
        pysh.sh("gunzip $log")
        uncompressed = log[:-3]
    else:
        print("Log", log, "is not compressed")
        uncompressed = log
    print(pysh.out("cat $uncompressed | grep -v 'CRDS  : ERROR    instrument'"))
    if log.endswith(".gz"):
        print("Recompressing", log)
        pysh.sh("gzip $uncompressed")
if __name__ == "__main__":
    main()

