#! /bin/csh

crds

echo =========================== svn info `pwd`  =========================
svn info
echo --------------------------- svn update --------------------------
svn update
echo --------------------------- svn status --------------------------
svn status

server

echo =========================== svn info `pwd`  =========================
svn info
echo --------------------------- svn update  -------------------------
svn update
echo --------------------------- svn status  -------------------------
svn status

