#! /bin/tcsh

# This script syncs an ops server to /grp/crds/${CRDS_PROJECT}.  Run on 
# test or dev servers,  the script exits w/o doing anything.

cd ${CRDS}/CRDS_server
source env.csh

setenv CRDS_PATH /grp/crds/${CRDS_PROJECT}
setenv CRDS_SERVER_URL https://${CRDS_PROJECT}-crds.stsci.edu

if ( ${CRDS_USECASE} != "ops" ) then
   echo "Skipping sync_ops_to_grp on ${CRDS_PROJECT} ${CRDS_USECASE} server."
   exit 0
endif

echo Syncing ${CRDS_SERVER} to ${CRDS_PATH}
python -m crds.list --config

cron_sync --all --fetch-references --verbose --stats  --push-context $CRDS_GRP_CACHE_KEY $* 
# add --check-sha1sum to be *really* sure
# add --purge-mappings, --purge-references to remove bogus files, use --dry-run --verbose to predict

echo Syncing CRDS sqlite3 database file.
cron_sync --fetch-sqlite-db

