#! /bin/tcsh

# This script syncs an ops server to /grp/crds/${CRDS_PROJECT}.  Run on 
# test or dev servers,  the script exits w/o doing anything.

cd ${CRDS}/CRDS_server
source env.csh

setenv CRDS_PATH /grp/crds/${CRDS_PROJECT}
setenv CRDS_SERVER_URL https://${CRDS_PROJECT}-crds.stsci.edu

if ( ${CRDS_USECASE} != "ops" ) then
   echo "Skipping sync_ops_to_grp on ${CRDS_PROJECT} ${CRDS_USECASE} server."
   exit 0
endif

echo Syncing ${CRDS_SERVER} to ${CRDS_PATH}
python -m crds.list --config

cron_sync --all --fetch-references --check-files --verbose --stats
# add --check-sha1sum to be *really* sure

echo "Setting file permissions"
chmod 444 ${CRDS_PATH}/mappings/${CRDS_PROJECT}/* >& /dev/null
chmod 444 ${CRDS_PATH}/references/${CRDS_PROJECT}/* >& /dev/null
chmod 644 ${CRDS_PATH}/config/${CRDS_PROJECT}/* >& /dev/null

