#! /usr/bin/env python
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division
from __future__ import absolute_import
from future import standard_library
standard_library.install_aliases()
from builtins import *

import sys

selected = [int(x) for x in sys.argv[1:]]

for line in sys.stdin:
        words = [w.strip() for w in line.split()]
        output = [ word for (i,word) in enumerate(words) if not selected or i in selected]
        joined= " ".join(output)
        if joined.strip():
                print(joined)

