#! /usr/bin/env python

import sys
import pyfits

def stub(fits):
    print "Deleting data in ", repr(fits)
    hdus = pyfits.open(fits)
    for hdu in hdus:
        hdu.data = None
    hdus.writeto(fits, clobber=True)

for fits in sys.argv[1:]:
    stub(fits)

