setenv PATH /home/jmiller/bin:/data1/pyetc_third_party_7/bin:/usr/stsci/Python-2.7.1/bin:/data2/iraf/pandokia/bin:/home/iraf/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin

setenv LD_LIBRARY_PATH /data1/pyetc_third_party_7/lib:/usr/stsci/Python-2.7.1/lib/

# setenv CRDS_www /home/jmiller/CRDS/CRDS_server/webserver

# setenv PYTHONPATH ${CRDS_www}/thirdparty/lib/python:${CRDS_www}/python/lib/python:/data1/pyetc_third_party_7/lib/python
setenv PYTHONPATH /data1/pyetc_third_party_7/lib/python

setenv apachemod /data1/pyetc_third_party_7/lib/apache/

setenv EDITOR emacs


