#!/bin/sh
#
# System startup script for pyetc - use this in /etc/rc.d
#
# chkconfig: 345 99 00
# description: start/stop all activated pyetc servers
# processname: pyetc_servers
#
# The chkconfig line shows 3 parameters:
#	list of run levels to enable by default
#	order to start this subsystem
#	order to stop this subsystem
# So, I think the 99 and 00 mean "start this last" and "stop it first".
#
# This script is intended for root to install, but the real work is
# handed off to scripts that run as the iraf user.
#

rc_dir=/data1/boot

case "$1" in
  start)
        echo "Starting  pyetc: "
	su iraf -c "$rc_dir/rc_script $1"
	echo ''
        ;;
  stop)
        echo "Shutting down pyetc: "
	su iraf -c "$rc_dir/rc_script $1"
	echo ''
        ;;
  status)
	su iraf -c "$rc_dir/rc_script $1"
        ;;
  *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
esac

exit 0
