#!/bin/tcsh
#
# System startup script for crds - use this in /etc/rc.d
#
# chkconfig: 345 99 00
# description: start/stop all activated crds servers
# processname: crds_server
#
# The chkconfig line shows 3 parameters:
#	list of run levels to enable by default
#	order to start this subsystem
#	order to stop this subsystem
# So, I think the 99 and 00 mean "start this last" and "stop it first".
#
# This script is intended for root to install, but the real work is
# handed off to scripts that run as the crds user.
#

rc_dir=/home/crds

switch ($1)
  case start:
    echo "Starting crds: "
	su crds -c "$rc_dir/rc_script $1"
	echo ''
    breaksw
  case stop:
    echo "Shutting down crds: "
	su crds -c "$rc_dir/rc_script $1"
	echo ''
    breaksw
  case status:
	su crds -c "$rc_dir/rc_script $1"
    breaksw
  default:
    echo "Usage: $0 {start|stop|status}"
    exit 1
    breaksw
endsw

exit 0
