#! /bin/tcsh
#
# This is the rc script that starts the CRDS web server at system boot time.
# This script is intended to be run by user "crds" in a login shell using su.
# Standard environment variables are set by the rc scripts of user crds,  most notably .setenv.
# The environment variables are driven by the uname of the VM where the server runs, e.g. tlhstcrdsv1
#

cd ${CRDS}/CRDS_server
source env.csh

case "$1" in
  start)
	./run
        ;;
  stop)
	./stop
        ;;
  status)
    sed 's/^/PID=/' < ${CRDS_INSTALL_DIR}/server/run/httpd.pid
        ;;
  *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
esac

exit 0
