#! /bin/tcsh

source ./env.csh

echo ">>>>> Adding fields to database."
cd ${CRDS_INSTALL_DIR}/python/lib/python/crds_server;
python -u manage.py dbshell <~/audit_blob.sql

server

python -u <<EOF
print ">>>>> pushing down blob fields to model fields"
from crds_server.interactive import models
for blob in models.AuditBlob.objects.all():
    blob.thaw().save()
EOF

cp ~/models.py sources/interactive

./rerun $1 $2

python -u <<EOF
print ">>>>> eliminating blob fields"
from crds_server.interactive import models
for blob in models.AuditBlob.objects.all():
    blob.thaw().save()
EOF

python -u <<EOF
print ">>>>> updating file states"
from crds_server.interactive import models
models.update_file_states()
EOF

