#! /bin/csh

source ~/.setenv

echo =================================== client  ===============================
crds
svn switch --relocate https://subversion.assembla.com/svn/crds/branches/milestone-5 https://aeon.stsci.edu/ssb/svn/crds/branches/milestone-5
svn info

echo =================================== server ===============================
server
svn switch --relocate https://subversion.assembla.com/svn/crds_server/branch/milestone-5 https://aeon.stsci.edu/ssb/svn/crds_server/branch/milestone-5
svn info
