CREATE TABLE archive_data_set_old_ver (
        ado_data_set_name               varchar(39)     NOT NULL,
        ado_archive_class               char(3)         NOT NULL,
        ado_generation_date             datetime        NOT NULL,
        ado_mission                     varchar(10)     NOT NULL,
        ado_instrument                  varchar(12)     NULL,
        ado_program_id                  char(3)         NULL,
        ado_obset_id                    char(2)         NULL,
        ado_obsnum                      char(3)         NULL,
        ado_pep_id                      int             NULL,
        ado_start_time                  datetime        NULL,
        ado_end_time                    datetime        NULL,
        ado_data_receipt_time           datetime        NULL,
        ado_completion_time             datetime        NULL,
        ado_best_version                char(1)         NULL,
        ado_data_set_size               float           NULL,
        ado_data_source                 varchar(6)      NULL,
        ado_file_count                  int             NULL,
        ado_build_num                   char(12)        NULL,
        ado_release_date                datetime        NULL,
        ado_release_date_mod            datetime        NULL,
        ado_proprietary_start_time      datetime        NULL,
        ado_delete_date                 datetime        NULL,
        ado_delete_comment              varchar(255)    NULL )
go
