CREATE TABLE cos_science (
        css_data_set_name               varchar(39)     NOT NULL,
        css_program_id                  char(3)         NOT NULL,
        css_obset_id                    char(2)         NOT NULL,
        css_obsnum                      char(3)         NOT NULL,
        css_acq_num                     smallint        NULL,
        css_acqiname                    varchar(10)     NULL,
        css_acqsname                    varchar(10)     NULL,
        css_aper_fov                    varchar(42)     NULL,
        css_aperture                    varchar(16)     NULL,
        css_date_obs                    datetime        NULL,
        css_dec_prop                    float           NULL,
        css_equinox                     float           NULL,
        css_exptimea                    float           NULL,
        css_exptimeb                    float           NULL,
        css_extended                    varchar(3)      NULL,
        css_losm1pos                    varchar(8)      NULL,
        css_losm2pos                    varchar(8)      NULL,
        css_maxwave                     float           NULL,
        css_minwave                     float           NULL,
        css_peakdnam                    varchar(10)     NULL,
        css_peakxnam                    varchar(10)     NULL,
        css_pequinox                    varchar(7)      NULL,
        css_postarg1                    float           NULL,
        css_postarg2                    float           NULL,
        css_primesi                     varchar(6)      NULL,
        css_propaper                    varchar(16)     NULL,
        css_ra_prop                     float           NULL,
        css_ss_aper                     varchar(16)     NULL,
        css_ss_cwave                    float           NULL,
        css_ss_dtctr                    varchar(10)     NULL,
        css_ss_grtng                    varchar(7)      NULL,
        css_ss_nstep                    smallint        NULL,
        css_hvlevela                    int             NULL,
        css_hvlevelb                    int             NULL )
go
