CREATE TABLE cos_tv_ref_data (
        ctr_data_set_name               varchar(39)     NOT NULL,
        ctr_backcorr                    varchar(8)      NULL,
        ctr_badtcorr                    varchar(8)      NULL,
        ctr_badttab                     varchar(23)     NULL,
        ctr_bpixtab                     varchar(23)     NULL,
        ctr_brftab                      varchar(23)     NULL,
        ctr_cenwave                     smallint        NULL,
        ctr_deadcorr                    varchar(8)      NULL,
        ctr_deadtab                     varchar(23)     NULL,
        ctr_detector                    varchar(3)      NULL,
        ctr_disptab                     varchar(23)     NULL,
        ctr_doppcorr                    varchar(8)      NULL,
        ctr_dqicorr                     varchar(8)      NULL,
        ctr_flatcorr                    varchar(8)      NULL,
        ctr_flatfile                    varchar(23)     NULL,
        ctr_fluxcorr                    varchar(8)      NULL,
        ctr_geocorr                     varchar(8)      NULL,
        ctr_geofile                     varchar(23)     NULL,
        ctr_helcorr                     varchar(8)      NULL,
        ctr_igeocorr                    varchar(8)      NULL,
        ctr_lamptab                     varchar(23)     NULL,
        ctr_obsmode                     varchar(10)     NULL,
        ctr_obstype                     varchar(14)     NULL,
        ctr_phacorr                     varchar(8)      NULL,
        ctr_phatab                      varchar(23)     NULL,
        ctr_phottab                     varchar(23)     NULL,
        ctr_proposid                    int             NULL,
        ctr_randcorr                    varchar(8)      NULL,
        ctr_randseed                    int             NULL,
        ctr_rptcorr                     varchar(8)      NULL,
        ctr_statflag                    char(1)         NULL,
        ctr_tempcorr                    varchar(8)      NULL,
        ctr_wavecorr                    varchar(8)      NULL,
        ctr_wcptab                      varchar(23)     NULL,
        ctr_x1dcorr                     varchar(8)      NULL,
        ctr_xtractab                    varchar(23)     NULL )
go
