CREATE TABLE fuse_exposures (
        fee_data_set_name               varchar(39)     NOT NULL,
        fee_archive_class               char(3)         NOT NULL,
        fee_asn_id                      varchar(11)     NOT NULL,
        fee_aperture                    char(4)         NULL,
        fee_aper_act                    char(4)         NULL,
        fee_det_mask                    char(5)         NULL,
        fee_expend                      datetime        NULL,
        fee_expendc                     varchar(5)      NULL,
        fee_expstart                    datetime        NULL,
        fee_exptime                     float           NULL,
        fee_exp_id                      char(3)         NULL,
        fee_exp_stat                    int             NULL,
        fee_fes_bin                     int             NULL,
        fee_fes_filt                    char(3)         NULL,
        fee_fes_tpos                    char(3)         NULL,
        fee_fp1lxpos                    float           NULL,
        fee_fp1sxpos                    float           NULL,
        fee_fp2lxpos                    float           NULL,
        fee_fp2sxpos                    float           NULL,
        fee_fpalxpos                    float           NULL,
        fee_fpalzpos                    float           NULL,
        fee_fpasxpos                    float           NULL,
        fee_fpaszpos                    float           NULL,
        fee_fpsplit                     char(1)         NULL,
        fee_instmode                    char(4)         NULL,
        fee_int_cal                     char(4)         NULL,
        fee_rawtime                     float           NULL,
        fee_rolloff                     float           NULL,
        fee_sia_tbl                     varchar(10)     NULL,
        fee_specbinx                    int             NULL,
        fee_specbiny                    int             NULL,
        fee_tacqseq                     varchar(80)     NULL,
        fee_total_cr                    float           NULL,
        fee_ttperiod                    float           NULL )

go
