CREATE TABLE nicmos_ref_data ( 
        nsr_data_set_name               varchar(39)     NOT NULL,
        nsr_program_id                  char(3)         NOT NULL,
        nsr_obset_id                    char(2)         NOT NULL,
        nsr_obsnum                      char(3)         NOT NULL,
        nsr_camera                      smallint        NULL,
        nsr_expstart                    datetime        NULL,
        nsr_filter                      varchar(7)      NULL,
        nsr_nread                       smallint        NULL,
        nsr_proposid                    int             NULL,
        nsr_readout                     char(4)         NULL,
        nsr_samp_seq                    char(8)         NULL,
        nsr_darkfile                    char(18)        NULL,
        nsr_flatfile                    char(18)        NULL,
        nsr_illmfile                    char(18)        NULL,
        nsr_maskfile                    char(18)        NULL,
        nsr_nlinfile                    char(18)        NULL,
        nsr_noisfile                    char(18)        NULL,
        nsr_pmodfile                    char(18)        NULL,
        nsr_pmskfile                    char(18)        NULL,
        nsr_saadfile                    char(18)        NULL,
        nsr_tdffile                     char(18)        NULL,
        nsr_tempfile                    char(18)        NULL,
        nsr_backtab                     char(18)        NULL,
        nsr_idctab                      char(18)        NULL,
        nsr_pedsbtab                    char(18)        NULL,
        nsr_phottab                     char(18)        NULL,
        nsr_rnlcortb                    char(18)        NULL,
        nsr_saacntab                    char(18)        NULL,
        nsr_zprattab                    char(18)        NULL,
        nsr_best_darkfile               char(18)        NULL,
        nsr_best_flatfile               char(18)        NULL,
        nsr_best_illmfile               char(18)        NULL,
        nsr_best_maskfile               char(18)        NULL,
        nsr_best_nlinfile               char(18)        NULL,
        nsr_best_noisfile               char(18)        NULL,
        nsr_best_pmodfile               char(18)        NULL,
        nsr_best_pmskfile               char(18)        NULL,
        nsr_best_saadfile               char(18)        NULL,
        nsr_best_tdffile                char(18)        NULL,
        nsr_best_tempfile               char(18)        NULL,
        nsr_best_backtab                char(18)        NULL,
        nsr_best_idctab                 char(18)        NULL,
        nsr_best_pedsbtab               char(18)        NULL,
        nsr_best_phottab                char(18)        NULL,
        nsr_best_rnlcortb               char(18)        NULL,
        nsr_best_saacntab               char(18)        NULL,
        nsr_best_zprattab               char(18)        NULL )
go
