CREATE TABLE science (
        sci_data_set_name               varchar(39)     NOT NULL,
        sci_archive_class               char(3)         NOT NULL,
        sci_program_id                  char(3)         NOT NULL,
        sci_obset_id                    char(2)         NOT NULL,
        sci_obsnum                      char(3)         NOT NULL,
        sci_asn_id                      varchar(10)     NULL,
        sci_targname                    varchar(30)     NULL,
        sci_target_descrip              varchar(160)    NULL,
        sci_broad_category              varchar(80)     NULL,
        sci_ra                          float           NULL,
        sci_dec                         float           NULL,
        sci_ra_v1                       float           NULL,
        sci_dec_v1                      float           NULL,
        sci_expflag                     varchar(24)     NULL,
        sci_start_time                  datetime        NULL,
        sci_stop_time                   datetime        NULL,
        sci_actual_duration             float           NULL,
        sci_instrume                    char(6)         NULL,
        sci_instrument_config           char(15)        NULL,
        sci_operating_mode              varchar(18)     NULL,
        sci_aper_1234                   varchar(60)     NULL,
        sci_spec_1234                   varchar(80)     NULL,
        sci_spectral_res                float           NULL,
        sci_spectrum_end                float           NULL,
        sci_spectrum_start              float           NULL,
        sci_bandwidth                   float           NULL,
        sci_central_wavelength          float           NULL,
        sci_dispersion                  float           NULL,
        sci_pixel_res                   float           NULL,
        sci_fgslock                     varchar(18)     NULL,
        sci_mtflag                      char(1)         NULL,
        sci_pep_id                      int             NULL,
        sci_pi_last_name                varchar(30)     NULL,
        sci_release_date                datetime        NULL,
        sci_v3_pos_angle                float           NULL,
        sci_ecliptic_latitude           float           NULL,
        sci_ecliptic_longitude          float           NULL,
        sci_galactic_latitude           float           NULL,
        sci_galactic_longitude          float           NULL,
        sci_sun_alt                     float           NULL,
        sci_pa_aper                     float           NULL,
        sci_costar_deploy               char(1)         NULL,
        sci_aec                         char(1)         NULL,
        sci_fov_config                  char(7)         NULL,
        sci_generation_date             datetime        NULL,
        sci_gyromode                    varchar(8)      NULL )
go
