CREATE TABLE wfc3_chip (
        w3c_data_set_name               varchar(39)     NOT NULL,
        w3c_program_id                  char(3)         NOT NULL,
        w3c_obset_id                    char(2)         NOT NULL,
        w3c_obsnum                      char(3)         NOT NULL,
        w3c_binaxis1                    smallint        NULL,
        w3c_binaxis2                    smallint        NULL,
        w3c_ccdchip                     smallint        NOT NULL,
        w3c_cd1_1                       float           NULL,
        w3c_cd1_2                       float           NULL,
        w3c_cd2_1                       float           NULL,
        w3c_cd2_2                       float           NULL,
        w3c_crpix1                      float           NULL,
        w3c_crpix2                      float           NULL,
        w3c_crval1                      float           NULL,
        w3c_crval2                      float           NULL,
        w3c_ctype1                      varchar(12)     NULL,
        w3c_ctype2                      varchar(12)     NULL,
        w3c_errcnt                      int             NULL,
        w3c_fillcnt                     int             NULL,
        w3c_goodmax                     float           NULL,
        w3c_goodmean                    float           NULL,
        w3c_goodmin                     float           NULL,
        w3c_ltm1_1                      float           NULL,
        w3c_ltm2_2                      float           NULL,
        w3c_ltv1                        float           NULL,
        w3c_ltv2                        float           NULL,
        w3c_meanblev                    float           NULL,
        w3c_meandark                    float           NULL,
        w3c_meanflsh                    float           NULL,
        w3c_ncombine                    smallint        NULL,
        w3c_ngoodpix                    int             NULL,
        w3c_orientat                    float           NULL,
        w3c_pa_aper                     float           NULL,
        w3c_photbw                      float           NULL,
        w3c_photflam                    float           NULL,
        w3c_photfnu                     float           NULL,
        w3c_photmode                    varchar(50)     NULL,
        w3c_photplam                    float           NULL,
        w3c_photzpt                     float           NULL,
        w3c_podpsff                     varchar(8)      NULL,
        w3c_sdqflags                    int             NULL,
        w3c_sizaxis1                    int             NULL,
        w3c_sizaxis2                    int             NULL,
        w3c_snrmax                      float           NULL,
        w3c_snrmean                     float           NULL,
        w3c_snrmin                      float           NULL,
        w3c_softerrs                    int             NULL,
        w3c_stdcfff                     varchar(8)      NULL,
        w3c_stdcffp                     varchar(8)      NULL,
        w3c_vafactor                    float           NULL,
        w3c_phtflam1                    float           NULL,
        w3c_phtflam2                    float           NULL,
        w3c_phtratio                    float           NULL )
go
