CREATE TABLE wfpc_ref_data (
        wcr_data_set_name               varchar(39)     NOT NULL,
        wcr_program_id                  char(3)         NOT NULL,
        wcr_obset_id                    char(2)         NOT NULL,
        wcr_obsnum                      char(3)         NOT NULL,
        wcr_camera                      char(2)         NULL,
        wcr_expstart                    datetime        NULL,
        wcr_filter1                     smallint        NULL,
        wcr_filter2                     smallint        NULL,
        wcr_imagetyp                    char(18)        NULL,
        wcr_mode                        char(4)         NULL,
        wcr_orientat_a                  float           NULL,
        wcr_orientat_b                  float           NULL,
        wcr_orientat_c                  float           NULL,
        wcr_orientat_d                  float           NULL,
        wcr_photmode_a                  char(48)        NULL,
        wcr_photmode_b                  char(48)        NULL,
        wcr_photmode_c                  char(48)        NULL,
        wcr_photmode_d                  char(48)        NULL,
        wcr_preftime                    float           NULL,
        wcr_proposid                    int             NULL,
        wcr_serials                     char(3)         NULL,
        wcr_shutter                     char(7)         NULL,
        wcr_atodcorr                    char(8)         NULL,
        wcr_biascorr                    char(8)         NULL,
        wcr_blevcorr                    char(8)         NULL,
        wcr_darkcorr                    char(8)         NULL,
        wcr_dophotom                    char(8)         NULL,
        wcr_maskcorr                    char(8)         NULL,
        wcr_prefcorr                    char(8)         NULL,
        wcr_purgcorr                    char(8)         NULL,
        wcr_atodfile                    char(18)        NULL,
        wcr_biasfile                    char(18)        NULL,
        wcr_blevfile                    char(18)        NULL,
        wcr_darkfile                    char(18)        NULL,
        wcr_flatfile                    char(18)        NULL,
        wcr_maskfile                    char(18)        NULL,
        wcr_preffile                    char(18)        NULL,
        wcr_purgfile                    char(18)        NULL,
        wcr_phottab                     char(18)        NULL,
        wcr_best_a2d                    char(18)        NULL,
        wcr_best_loc_a2d                varchar(9)      NULL,
        wcr_best_bas                    char(18)        NULL,
        wcr_best_loc_bas                varchar(9)      NULL,
        wcr_best_drk                    char(18)        NULL,
        wcr_best_loc_drk                varchar(9)      NULL,
        wcr_best_flt                    char(18)        NULL,
        wcr_best_loc_flt                varchar(9)      NULL,
        wcr_best_msk                    char(18)        NULL,
        wcr_best_loc_msk                varchar(9)      NULL,
        wcr_best_prf                    char(18)        NULL,
        wcr_best_loc_prf                varchar(9)      NULL,
        wcr_best_pur                    char(18)        NULL,
        wcr_best_loc_pur                varchar(9)      NULL,
        wcr_best_phottab                char(18)        NULL,
        wcr_best_loc_photmode_a         varchar(9)      NULL,
        wcr_best_loc_photmode_b         varchar(9)      NULL,
        wcr_best_loc_photmode_c         varchar(9)      NULL,
        wcr_best_loc_photmode_d         varchar(9)      NULL )
go
