CREATE TABLE acs_chip (
        acc_program_id                  char(3)         NOT NULL,
        acc_obset_id                    char(2)         NOT NULL,
        acc_obsnum                      char(3)         NOT NULL,
        acc_binaxis1                    smallint        NULL,
        acc_binaxis2                    smallint        NULL,
        acc_cblksiz                     int             NULL,
        acc_ccdchip                     smallint        NOT NULL,
        acc_cd1_1                       float           NULL,
        acc_cd1_2                       float           NULL,
        acc_cd2_1                       float           NULL,
        acc_cd2_2                       float           NULL,
        acc_centera1                    int             NULL,
        acc_centera2                    int             NULL,
        acc_comptyp                     varchar(8)      NULL,
        acc_crpix1                      float           NULL,
        acc_crpix2                      float           NULL,
        acc_crval1                      float           NULL,
        acc_crval2                      float           NULL,
        acc_errcnt                      int             NULL,
        acc_fillcnt                     int             NULL,
        acc_goodmax                     float           NULL,
        acc_goodmean                    float           NULL,
        acc_goodmin                     float           NULL,
        acc_lostpix                     int             NULL,
        acc_ltm1_1                      float           NULL,
        acc_ltm2_2                      float           NULL,
        acc_ltv1                        float           NULL,
        acc_ltv2                        float           NULL,
        acc_meanblev                    float           NULL,
        acc_meandark                    float           NULL,
        acc_meanflsh                    float           NULL,
        acc_ncombine                    smallint        NULL,
        acc_ngoodpix                    int             NULL,
        acc_orientat                    float           NULL,
        acc_pa_aper                     float           NULL,
        acc_photbw                      float           NULL,
        acc_photflam                    float           NULL,
        acc_photmode                    varchar(50)     NULL,
        acc_photplam                    float           NULL,
        acc_photzpt                     float           NULL,
        acc_podpsff                     char(1)         NULL,
        acc_sdqflags                    int             NULL,
        acc_sizaxis1                    int             NULL,
        acc_sizaxis2                    int             NULL,
        acc_snrmax                      float           NULL,
        acc_snrmean                     float           NULL,
        acc_snrmin                      float           NULL,
        acc_softerrs                    int             NULL,
        acc_stdcfff                     char(1)         NULL,
        acc_stdcffp                     char(6)         NULL,
        acc_vafactor                    float           NULL,
        acc_wfcmprsd                    char(1)         NULL,
        acc_mdrizsky                    float           NULL )
go
