CREATE TABLE archive_data_set_log_del (
        adl_data_set_name               varchar(39)     NOT NULL,
        adl_archive_class               char(3)         NOT NULL,
        adl_generation_date             datetime        NOT NULL,
        adl_mission                     varchar(10)     NOT NULL,
        adl_instrument                  varchar(12)     NULL,
        adl_program_id                  char(3)         NULL,
        adl_obset_id                    char(2)         NULL,
        adl_obsnum                      char(3)         NULL,
        adl_pep_id                      int             NULL,
        adl_start_time                  datetime        NULL,
        adl_end_time                    datetime        NULL,
        adl_data_receipt_time           datetime        NULL,
        adl_completion_time             datetime        NULL,
        adl_best_version                char(1)         NULL,
        adl_data_set_size               float           NULL,
        adl_data_source                 varchar(6)      NULL,
        adl_file_count                  int             NULL,
        adl_build_num                   char(12)        NULL,
        adl_release_date                datetime        NULL,
        adl_release_date_mod            datetime        NULL,
        adl_proprietary_start_time      datetime        NULL,
        adl_asn_id                      varchar(20)     NULL,
        adl_asn_status                  varchar(10)     NULL,
        adl_log_delete_date             datetime        NULL,
        adl_log_delete_comment          varchar(255)    NULL )
go
