CREATE TABLE foc_ref_data (
        fcr_data_set_name               varchar(39)     NOT NULL,
        fcr_program_id                  char(3)         NOT NULL,
        fcr_obset_id                    char(2)         NOT NULL,
        fcr_obsnum                      char(3)         NOT NULL,
        fcr_cammode                     char(7)         NULL,
        fcr_expstart                    datetime        NULL,
        fcr_filtnam1                    char(8)         NULL,
        fcr_filtnam2                    char(8)         NULL,
        fcr_filtnam3                    char(8)         NULL,
        fcr_filtnam4                    char(8)         NULL,
        fcr_kxdeploy                    char(1)         NULL,
        fcr_ledcolor                    char(10)        NULL,
        fcr_ledmode                     char(7)         NULL,
        fcr_lineoff                     float           NULL,
        fcr_linepfm                     smallint        NULL,
        fcr_optcrly                     char(3)         NULL,
        fcr_optelt1                     smallint        NULL,
        fcr_optelt2                     smallint        NULL,
        fcr_orientat                    float           NULL,
        fcr_photbw                      float           NULL,
        fcr_photplam                    float           NULL,
        fcr_proposid                    int             NULL,
        fcr_pxformt                     char(7)         NULL,
        fcr_samppln                     smallint        NULL,
        fcr_sampoff                     float           NULL,
        fcr_shtmode                     char(7)         NULL,
        fcr_smmmode                     char(7)         NULL,
        fcr_baccorr                     char(8)         NULL,
        fcr_geocorr                     char(8)         NULL,
        fcr_itfcorr                     char(8)         NULL,
        fcr_pxlcorr                     char(8)         NULL,
        fcr_sdecorr                     char(8)         NULL,
        fcr_unicorr                     char(8)         NULL,
        fcr_bachfile                    char(18)        NULL,
        fcr_blmhfile                    char(18)        NULL,
        fcr_geohfile                    char(18)        NULL,
        fcr_itfhfile                    char(18)        NULL,
        fcr_sdehfile                    char(18)        NULL,
        fcr_unihfile                    char(18)        NULL,
        fcr_comptab                     char(18)        NULL,
        fcr_graphtab                    char(18)        NULL,
        fcr_unitab                      char(18)        NULL,
        fcr_best_bac                    char(18)        NULL,
        fcr_best_loc_bac                varchar(9)      NULL,
        fcr_best_blm                    char(18)        NULL,
        fcr_best_loc_blm                varchar(9)      NULL,
        fcr_best_geo                    char(18)        NULL,
        fcr_best_loc_geo                varchar(9)      NULL,
        fcr_best_itf                    char(18)        NULL,
        fcr_best_loc_itf                varchar(9)      NULL,
        fcr_best_sde                    char(18)        NULL,
        fcr_best_loc_sde                varchar(9)      NULL,
        fcr_best_uni                    char(18)        NULL,
        fcr_best_loc_uni                varchar(9)      NULL,
        fcr_best_comptab                char(18)        NULL,
        fcr_best_loc_comptab            varchar(9)      NULL,
        fcr_best_graphtab               char(18)        NULL,
        fcr_best_loc_graphtab           varchar(9)      NULL,
        fcr_best_unitab                 char(18)        NULL,
        fcr_best_loc_unitab             varchar(9)      NULL )
go
