CREATE TABLE hsp_ref_data ( 
        hpr_data_set_name               varchar(39)     NOT NULL,
        hpr_program_id                  char(3)         NOT NULL,
        hpr_obset_id                    char(2)         NOT NULL,
        hpr_obsnum                      char(3)         NOT NULL,
        hpr_apertobj                    char(10)        NULL,
        hpr_data_fmt                    char(4)         NULL,
        hpr_data_src                    char(9)         NULL,
        hpr_data_typ                    char(7)         NULL,
        hpr_detectob                    smallint        NULL,
        hpr_expstart                    datetime        NULL,
        hpr_mode                        char(3)         NULL,
        hpr_proposid                    int             NULL,
        hpr_thresh                      int             NULL,
        hpr_samptime                    float           NULL,
        hpr_vgaind                      smallint        NULL,
        hpr_voltage                     int             NULL,
        hpr_ccp0                        char(18)        NULL,
        hpr_ccp1                        char(18)        NULL,
        hpr_ccp2                        char(18)        NULL,
        hpr_ccp3                        char(18)        NULL,
        hpr_ccp4                        char(18)        NULL,
        hpr_ccp5                        char(18)        NULL,
        hpr_ccp7                        char(18)        NULL,
        hpr_ccp8                        char(18)        NULL,
        hpr_ccp9                        char(18)        NULL,
        hpr_comptab                     char(18)        NULL,
        hpr_graphtab                    char(18)        NULL,
        hpr_best_ccp0                   char(18)        NULL,
        hpr_best_loc_ccp0               varchar(9)      NULL,
        hpr_best_ccp1                   char(18)        NULL,
        hpr_best_loc_ccp1               varchar(9)      NULL,
        hpr_best_ccp2                   char(18)        NULL,
        hpr_best_loc_ccp2               varchar(9)      NULL,
        hpr_best_ccp3                   char(18)        NULL,
        hpr_best_loc_ccp3               varchar(9)      NULL,
        hpr_best_ccp4                   char(18)        NULL,
        hpr_best_loc_ccp4               varchar(9)      NULL,
        hpr_best_ccp5                   char(18)        NULL,
        hpr_best_loc_ccp5               varchar(9)      NULL,
        hpr_best_ccp7                   char(18)        NULL,
        hpr_best_loc_ccp7               varchar(9)      NULL,
        hpr_best_ccp8                   char(18)        NULL,
        hpr_best_loc_ccp8               varchar(9)      NULL,
        hpr_best_ccp9                   char(18)        NULL,
        hpr_best_loc_ccp9               varchar(9)      NULL,
        hpr_best_comptab                char(18)        NULL,
        hpr_best_loc_comptab            varchar(9)      NULL,
        hpr_best_graphtab               char(18)        NULL,
        hpr_best_loc_graphtab           varchar(9)      NULL )
go
