CREATE TABLE registered_users (
        rgu_user_id                     varchar(31)     NOT NULL,
        rgu_pswd                        varchar(64)     NULL,
        rgu_paswdreq                    char(5)         NOT NULL,
        rgu_superuser                   varchar(12)     NOT NULL,
        rgu_lname                       varchar(24)     NOT NULL,
        rgu_mname                       varchar(24)     NULL,
        rgu_fname                       varchar(24)     NULL,
        rgu_title                       char(5)         NULL,
        rgu_phone                       varchar(20)     NULL,
        rgu_fax                         varchar(20)     NULL,
        rgu_inst                        varchar(80)     NOT NULL,
        rgu_email                       varchar(80)     NOT NULL,
        rgu_addr1                       varchar(80)     NOT NULL,
        rgu_addr2                       varchar(80)     NULL,
        rgu_addr3                       varchar(80)     NULL,
        rgu_country                     varchar(20)     NOT NULL,
        rgu_expiration                  datetime        NULL,
        rgu_user_type                   char(1)         NOT NULL,
        rgu_byte_limit                  int             NOT NULL,
        rgu_total_bytes                 int             NULL,
        rgu_nrequests                   int             NOT NULL,
        rgu_last_act                    datetime        NULL,
        rgu_priority                    int             NOT NULL )
go
