CREATE TABLE wfc3_tv_ref_data (
        wtr_data_set_name               varchar(39)     NOT NULL,
        wtr_binaxis1                    smallint        NULL,
        wtr_binaxis2                    smallint        NULL,
        wtr_atodcorr                    varchar(8)      NULL,
        wtr_atodtab                     varchar(23)     NULL,
        wtr_biascorr                    varchar(8)      NULL,
        wtr_biasfile                    varchar(23)     NULL,
        wtr_blevcorr                    varchar(8)      NULL,
        wtr_bpixtab                     varchar(23)     NULL,
        wtr_ccdamp                      varchar(4)      NULL,
        wtr_ccdgain                     float           NULL,
        wtr_ccdtab                      varchar(23)     NULL,
        wtr_comptab                     varchar(23)     NULL,
        wtr_crcorr                      varchar(8)      NULL,
        wtr_crrejtab                    varchar(23)     NULL,
        wtr_darkcorr                    varchar(8)      NULL,
        wtr_darkfile                    varchar(23)     NULL,
        wtr_detector                    varchar(4)      NULL,
        wtr_dfltfile                    varchar(23)     NULL,
        wtr_dqicorr                     varchar(8)      NULL,
        wtr_drizcorr                    varchar(8)      NULL,
        wtr_expscorr                    varchar(8)      NULL,
        wtr_filter                      varchar(7)      NULL,
        wtr_flatcorr                    varchar(8)      NULL,
        wtr_flshcorr                    varchar(8)      NULL,
        wtr_flshfile                    varchar(23)     NULL,
        wtr_graphtab                    varchar(23)     NULL,
        wtr_idctab                      varchar(23)     NULL,
        wtr_iulgatab                    int             NULL,
        wtr_lfltfile                    varchar(23)     NULL,
        wtr_nlincorr                    varchar(8)      NULL,
        wtr_nlinfile                    varchar(23)     NULL,
        wtr_oscntab                     varchar(23)     NULL,
        wtr_pfltfile                    varchar(23)     NULL,
        wtr_photcorr                    varchar(8)      NULL,
        wtr_proposid                    int             NULL,
        wtr_rptcorr                     varchar(8)      NULL,
        wtr_samp_seq                    varchar(8)      NULL,
        wtr_shadcorr                    varchar(8)      NULL,
        wtr_shadfile                    varchar(23)     NULL,
        wtr_unitcorr                    varchar(8)      NULL,
        wtr_subtype                     varchar(8)      NULL,
        wtr_zoffcorr                    varchar(8)      NULL,
        wtr_zsigcorr                    varchar(8)      NULL )
go
