#! /usr/bin/env python
#-*-python-*-

# Add a list of users to the specified group in Django authentication

import sys

from django.contrib.auth.models import User, Group

def add_users(group, users):
    g = Group.objects.get(name=group)
    for user in users:
        u = User.objects.get(username=user)
    	g.user_set.add(u.id)

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("usage: add_group <group> <users...>")
        sys.exit(1)
    else:
        add_users(sys.argv[1], sys.argv[2:])
