#! /usr/bin/env python

"""This is a quick and dirty script for checking the consistency of a CRDS
'deliveries' directory with the catalog and
"""

from __future__ import print_function

import glob
from crds_server.interactive import models

delivered = set(open("delivered").read().splitlines())

cataloged = set()
for f in glob.glob("*.cat"):
    cataloged |= set(open(f).read().splitlines())

print("File delivered but not .cat'ed:", delivered - cataloged)

print (".cat'ed but no file delivered:",  cataloged - delivered)

database_filenames = set(models.get_fileblob_map().keys())

print("Database but not .cat'ed", database_filenames - cataloged)

print(".cat'ed but not database", cataloged - database_filenames)

print("Database but not delivered", database_filenames - delivered)

print("Delivered but not database", delivered - database_filenames)

blobmap = models.get_fileblob_map()
for f in set((database_filenames - delivered)|(database_filenames-cataloged)):
    print(f, blobmap[f].description)

