#! /usr/bin/env python 
#-*-python-*-

"""Script for cross-checking various HST file property determination methods."""

import sys

from crds import pysh
from crds.hst import locate

def main(instruments):
    for instrument in instruments:
        locate.check_naming_consistency(instrument)

if __name__ == "__main__":
    if len(sys.argv) == 1:
        instruments = [None]
    else:
        instruments = sys.argv[1:]
    main(instruments)
