#! /usr/bin/env python
import sys

from crds import pysh, log
from crds_server.crds_database import DATABASES

def dump(databases=["default"]):
    for dbname, pars in DATABASES.items():
        if "mysql" in pars["ENGINE"] and dbname in databases:
            host = pars["HOST"]
            port = pars["PORT"]
            user = pars["USER"]
            password = pars["PASSWORD"]
            name = pars["NAME"]
            log.info("Dumping", repr(name), "from", repr(host))
            pysh.sh("mysqldump --host='${host}' --port='${port}' --user='${user}' --password='${password}' ${name} >${name}.dump")

if __name__ == "__main__":
    dump(sys.argv[1:] or ["default"])

