#! /usr/bin/env python
#-*-Python-*-
import sys
import os.path

import pyfits

from crds import log, utils, pysh, timestamp

def setval(filepath, key, value):
    log.info("Setting", repr(filepath), key, "=", repr(value))
    pyfits.setval(filepath, keyword=key, value=value)

def main():
    for filepath in sys.argv[1:]:
        with log.error_on_exception("Fixing", filepath, "failed."):
            assert os.path.exists(filepath), "Bad filepath " + repr(filepath)

            parts = os.path.basename(filepath).split("_")
            observatory, instrument, filekind, serial_ext = parts
            
            locate = utils.get_object("crds", observatory, "locate")
            
            assert observatory in ["hst","jwst"], "Bad observatory " + repr(observatory)
            assert instrument in locate.INSTRUMENTS, "Bad instrument " + repr(instrument)
            assert filekind in locate.FILEKINDS, "Bad filekind " + repr(filekind)
            
            setval(filepath, "INSTRUME", instrument.upper())
            setval(filepath, "COMMENT", "a comment")
            setval(filepath, "DESCRIP", "a description")
            setval(filepath, "PEDIGREE", "DUMMY")
            setval(filepath, "USEAFTER", "1990-01-01 12:00:00")
            
            if observatory == "jwst":
                reftype = locate.filekind_to_reftype(filekind)
                setval(filepath, "REFTYPE", reftype)
                
if __name__ == "__main__":
    main()
