#! /bin/tcsh -x

source env.csh

chmod +w ${CRDS_PATH}/references/jwst/*
cp $1/*.fits ${CRDS_PATH}/references/jwst
chmod -w ${CRDS_PATH}/references/jwst/*

chmod +w ${CRDS_PATH}/mappings/jwst/*
cp $1/*.*map ${CRDS_PATH}/mappings/jwst
chmod -w ${CRDS_PATH}/mappings/jwst/*

rm -f ${CRDS_PATH}/catalogs/*
rm -f ${CRDS_PATH}/deliveries/*

python tools/wipe_db.py

./init jwst test

