#! /usr/bin/env python

"""
This script is run something like this:

python -m crds.diff hst.pmap hst_0000.pmap --print-new-files | ../tools/link_hst_diffs --link

It creates instrument directories containing links to new CDBS references under /grp/hst/cdbs.

New references are those which were (a) added or (b) replacements.
"""

import sys
import os

from crds.hst import locate
from crds import rmap, pysh

def main():
    for line in sys.stdin.readlines():
        filename, instrument = line.split()[:2]
        if not rmap.is_mapping(filename):
            path = locate.locate_server_reference(filename)
        else:
            path = rmap.locate_mapping(filename)
        print path
        if "--link" in sys.argv:
            pysh.sh("mkdir ${instrument}")
            os.symlink(path, instrument + "/" + os.path.basename(path))

main()

