#! /usr/bin/env python
#-*-python-*-

# list out the usernames of all the current users in Django auth

# XXX add switches to beef up functionality

from django.contrib.auth.models import User

def list_users():
    for user in User.objects.all():
        print(user.username)

if __name__ == "__main__":
    list_users()
