#! /usr/bin/env python
#-*-python-*-

import os, sys
import os.path
import glob

from crds import log
from crds_server import config
from crds_server.interactive import models

def get_catalogs():
    return glob.glob(os.path.join(config.CRDS_CATALOG_DIR, "*.cat"))

def link_updates():
    updates = []
    for catalog in get_catalogs():
    	delivery_catalog = os.path.join(config.CRDS_DELIVERY_DIR, os.path.basename(catalog))
    	for fname in open(catalog).read().splitlines():
	    updates.append((fname, delivery_catalog))
    return updates

def set_catalog_links():
    blobs = models.get_fileblob_map()
    for fname, delivery_catalog in link_updates():
    	blobs[fname].thaw()
	if blobs[fname].catalog_link == "":
	   log.info("Repairing", repr(fname), "to", repr(delivery_catalog))
	   blobs[fname].catalog_link = delivery_catalog
	   blobs[fname].save()

if __name__ == "__main__":
    set_catalog_links()

