#! /bin/csh

# usage:   tools/restore_server
# restores the last nightly backup for this server.

cd ${CRDS}/CRDS_server
source env.csh
tools/mirror_server ${CRDS_PROJECT} ${CRDS_USECASE} ${CRDS_SERVER_URL}
