#! /bin/csh

# usage:   tools/restore_server
# restores the last nightly backup for this server.

set BACKUP_DIR=$HOME/backups

cd $CRDS_INSTALL_DIR/CRDS_server
source env.csh

set observatory=$CRDS_PROJECT
set server_mode=$CRDS_USECASE
set mirrored_server_url=$CRDS_SERVER_URL

set database_backup_file=${BACKUP_DIR}/backup.${observatory}.${server_mode}.mysql 
set catalog_file=${BACKUP_DIR}/catalogs.${observatory}.${server_mode}.tar.gz
set deliveries_file=${BACKUP_DIR}/deliveries.${observatory}.${server_mode}.txt

set BACKUP_PORT=8002   # vs. nominal operational port 8001
set ORIGINAL_PORT=$SERVER_PORT

cd ${CRDS}/CRDS_server
source env.csh

echo "------------------------------------------------------------------"
echo "Restarting server ${CRDS_PROJECT} ${CRDS_USECASE} on private ports"
echo "------------------------------------------------------------------"
tools/set_backup_url True

# switch over to backup port
source env.csh
# setenv CRDS_SERVER_URL https://${CRDS_SERVER}:${BACKUP_PORT}

# This replaces the local database with the specified backup, presumably from the master server
echo "-----------------------------------------------------"
echo "Restoring database from $database_backup_file"
echo "-----------------------------------------------------"
cd ${CRDS}/CRDS_server
./manage dbrestore -f $database_backup_file

# This synchronizes the local cache to the master server
echo "-----------------------------------------------------"
echo "Syncing mappings from $mirrored_server_url"
echo "-----------------------------------------------------"
cd ${CRDS}/CRDS_server
python -m crds.sync --all --repair-files --check-sha1sum --purge-mappings --verbose 

echo "-----------------------------------------------------"
echo "Fast-Syncing references from $mirrored_server_url"
echo "-----------------------------------------------------"
# setenv CRDS_DOWNLOAD_CHECKSUMS 0    # Omit sha1sum verification on initial download
cd ${CRDS}/CRDS_server
python -m crds.sync --all --repair-files --fetch-references --purge-references --purge-mappings --verbose 

# This checks the consistency of the database and server cache and delivery areas
echo "-----------------------------------------------------"
echo "Checking and purging orphan files."
echo "-----------------------------------------------------"
cd ${CRDS}/CRDS_server
tools/orphan_files #  --purge-delivery-errors

# This recreates the catalogs directory from a backup tarball.
echo "-----------------------------------------------------"
echo "Copying catalog files from backup"
echo "-----------------------------------------------------"
cd ${CRDS_PATH}/../server_files
rm -rf catalogs
tar zxvf $catalog_file

# This recreates the delivery directory with files from the database which are
# recorded as not-yet-delivered.
echo "-----------------------------------------------------"
echo "Recreating delivery directory and delivering files in state 'delivered'."
echo "-----------------------------------------------------"
cd ${CRDS_PATH}/../server_files
rm -rf deliveries
mkdir deliveries
cd ${CRDS}/CRDS_server
# tools/redeliver_catalogs --find-undelivered-catalogs
tools/redeliver_catalogs --files `cat $deliveries_file`

echo "-----------------------------------------------------"
echo "Rechecking orphan files."
echo "-----------------------------------------------------"
cd ${CRDS}/CRDS_server
tools/orphan_files

echo "-----------------------------------------------------"
echo "Re-installing and restarting server ${CRDS_PROJECT} ${CRDS_USECASE}"
echo "-----------------------------------------------------"
tools/set_backup_url False

