#! /bin/csh

# usage:   tools/restore_backup
# restores the last nightly backup for this server.

set BACKUP_DIR=$HOME/backups

cd ${CRDS}/CRDS_server
source env.csh

tools/mirror_server $CRDS_PROJECT $CRDS_USECASE $CRDS_SERVER_URL

