#! /bin/tcsh -fx

setenv CONDA_NAME crds_conda3-6

setenv CRDS_STACK ${CRDS}/crds_stacks/$CONDA_NAME
setenv META_PREFIX ${CRDS_STACK}

cd ${CRDS}/crds_stacks
rm -rf ${CRDS_STACK}.old
mv ${CRDS_STACK} ${CRDS_STACK}.old
rm -rf installer4
cp -r /eng/ssb/crds/installer4 .
cd installer4/build
git checkout $CONDA_NAME

rm -f *.err
./meta clean >& /dev/null

# Set up miniconda
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ./miniconda3.sh
bash ./miniconda3.sh -b -p $CRDS_STACK
rm miniconda.sh
setenv PATH ${CRDS_STACK}/bin:${PATH}
rehash 

conda install --quiet --yes --file ${CONDA_NAME}.txt
conda remove --quiet --yes crds

./meta install @crds3-fixed  |& tee ${CRDS_STACK}/crds3.err
./meta install jwst |& tee ${CRDS_STACK}/jwst.err
./meta clean >& /dev/null

rehash

git status  |& tee ${CRDS_STACK}/git.status
git log --stat |& tee ${CRDS_STACK}/git.log
conda list --explicit |& tee ${CRDS_STACK}/${CONDA_NAME}.txt


# Install the entire base to get mercurial... for this.
# ../src/pull_local

