#! /bin/tcsh -fx

setenv CONDA_NAME crds_conda3-8

setenv CRDS_STACK ${CRDS}/crds_stacks/$CONDA_NAME
setenv META_PREFIX ${CRDS_STACK}

cd ${CRDS}/crds_stacks
cd installer4/build
git checkout $CONDA_NAME

rm -f *.err
./meta clean >& /dev/null

cd ${CRDS}/crds_stacks/installer4/conda-sources
bash miniconda3.sh -b -p $CRDS_STACK
setenv PATH ${CRDS_STACK}/bin:${PATH}
rehash 

# conda config --add channels http://ssb.stsci.edu/astroconda
conda config --add channels http://ssb.stsci.edu/conda-dev 
# conda create --name $CONDA_NAME --file $CONDA_NAME.files.txt

cd linux-64
conda install --use-local ./*.bz2

cd ${CRDS}/crds_stacks/installer4/build
git checkout $CONDA_NAME

./meta install @crds3-fixed  |& tee crds3.err
./meta install jwst |& tee jwst.err
./meta install cfitsio fitsverify |& tee fitsverify.err

conda uninstall --yes --quiet pkg-config pkgconfig
pip uninstall --yes Django

./meta install mod_wsgi-master |& tee mod_wsgi.err
./meta install Django
./meta clean >& /dev/null

conda remove --yes --force unixodbc  # pulled in by pyodbc,  use stock installtion provided by DATB instead.
cp /usr/etc/odbc.ini /home/crds/.odbc.ini
cp /usr/etc/odbcinst.ini /home/crds/.odbcinst.ini
rehash

git status  |& tee git.status
git log --stat |& tee git.log

