#! /bin/tcsh -fx

setenv CONDA_NAME crds_conda3-8

setenv CRDS_STACK ${CRDS}/crds_stacks/$CONDA_NAME
setenv META_PREFIX ${CRDS_STACK}

cd ${CRDS}/crds_stacks
rm -rf ${CRDS_STACK}.old
mv ${CRDS_STACK} ${CRDS_STACK}.old
rm -rf installer4
cp -r /eng/ssb/crds/installer4 .
cd installer4/build
git checkout $CONDA_NAME

rm -f *.err
./meta clean >& /dev/null

# Set up miniconda
mkdir -p ${CRDS}/crds_stacks/installer4/conda-sources
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    -O ${CRDS}/crds_stacks/installer4/conda-sources/miniconda3.sh
bash ${CRDS}/crds_stacks/installer4/conda-sources/miniconda3.sh -b -p $CRDS_STACK
setenv PATH ${CRDS_STACK}/bin:${PATH}
rehash 

# conda config --add channels http://ssb.stsci.edu/astroconda
conda config --add channels http://ssb.stsci.edu/conda-dev 
conda install stsci jwst --quiet --yes
conda install astropy numpy scipy asdf gwcs ipython requests lxml pymysql --quiet --yes

# conda install fitsverify cfitsio --quiet --yes

# conda install --quiet --yes --file ${CRDS}/CRDS_server/host/${CONDA_NAME}.pkgs
# conda install --quiet --yes --file http://ssb.stsci.edu/conda/jwstdp-0.7.0rc/jwstdp-0.7.0rc2-linux-py27.0.txt

conda remove --quiet --yes --force cfitsio fitsverify jwst
conda install --yes --quiet setuptools

cd ${CRDS}/crds_stacks/installer4/build

./meta install @crds3-fixed  |& tee crds3.err
./meta install jwst |& tee jwst.err
./meta install cfitsio fitsverify |& tee fitsverify.err

conda uninstall --yes --quiet pkg-config pkgconfig
pip uninstall --yes Django

./meta install mod_wsgi-master |& tee mod_wsgi.err
./meta install Django
./meta clean >& /dev/null

conda remove --yes --force unixodbc  # pulled in by pyodbc,  use stock installtion provided by DATB instead.
cp /usr/etc/odbc.ini /home/crds/.odbc.ini
cp /usr/etc/odbcinst.ini /home/crds/.odbcinst.ini
rehash

git status  |& tee git.status
git log --stat |& tee git.log
conda list --explicit |& tee ${CONDA_NAME}.txt

./joes_download ${CONDA_NAME}.txt ${CRDS}/crds_stacks/installer4/conda-sources

# Install the entire base to get mercurial... for this.
# ../src/pull_local

